import Foundation

class WordStore {
    private static let wordsKey = "saved_words"
    private static let statsKey = "quiz_stats"
    
    static func save(words: [Word]) {
        if let data = try? JSONEncoder().encode(words) {
            UserDefaults.standard.set(data, forKey: wordsKey)
        }
    }
    
    static func load() -> [Word] {
        guard let data = UserDefaults.standard.data(forKey: wordsKey),
              let words = try? JSONDecoder().decode([Word].self, from: data) else {
            return defaultWords()
        }
        return words
    }
    
    static func saveStats(_ stats: QuizStats) {
        if let data = try? JSONEncoder().encode(stats) {
            UserDefaults.standard.set(data, forKey: statsKey)
        }
    }
    
    static func loadStats() -> QuizStats {
        guard let data = UserDefaults.standard.data(forKey: statsKey),
              let stats = try? JSONDecoder().decode(QuizStats.self, from: data) else {
            return QuizStats()
        }
        return stats
    }
    
    static func defaultWords() -> [Word] {
        [
        Word(english: "executive", korean: "(명) 경영진, 임원 / (형) 경영의, 운영의"),
        Word(english: "inventory", korean: "(명) 재고, 재고 목록 / (명) 재고 조사"),
        Word(english: "feature", korean: "(명) 특징, 특색 / (명) 특집 기사"),
        Word(english: "acknowledge", korean: "(동) 수신을 인정하다 / (동) 감사를 표현하다"),
        Word(english: "voucher", korean: "(명) 상품권, 바우처 / (명) 영수증, 증명서"),
        Word(english: "estimate", korean: "(명) 견적서, 평가 / (동) 추산하다, 평가하다"),
        Word(english: "resume", korean: "(동) 재개하다 / (명) 이력서"),
        Word(english: "issue", korean: "(명) 문제, 이슈 / (동) 발행하다"),
        Word(english: "property", korean: "(명) 재산, 소유물 / (명) 부동산"),
        Word(english: "eligible", korean: "(형) 자격이 있는 / (형) 적격의"),
        Word(english: "initiative", korean: "(명) 주도권 / (명) 새로운 계획, 선도적 행 동"),
        Word(english: "culinary", korean: "(형) 요리의, 음식의"),
        Word(english: "extensive", korean: "(형) 광범위한 / (형) 대규모의"),
        Word(english: "deposit", korean: "(명) 예치금, 보증금 / (명) 침전물"),
        Word(english: "retail", korean: "(명) 소매 / (형) 소매의"),
        Word(english: "affordable", korean: "(형) 가격이 알맞은"),
        Word(english: "grant", korean: "(동) 승인하다 / (동) 수여하다"),
        Word(english: "significantly", korean: "(부) 상당히, 현저하게 / (부) 중요한 정도로, 의미 있 게"),
        Word(english: "reserve", korean: "(동) 예약하다 / (동) 보유하다"),
        Word(english: "application", korean: "(명) 신청, 지원서 / (명) 적용, 응용"),
        Word(english: "address", korean: "(명) 주소 / (동) 문제를 다루다"),
        Word(english: "suppose", korean: "(동) 추정하다 / (동) 생각하다"),
        Word(english: "charge", korean: "(명) 요금 / (명) 책임"),
        Word(english: "expire", korean: "(동) 기한이 만료되다 / (동) 효력이 끝나다"),
        Word(english: "refund", korean: "(명) 환불 / (동) 환불하다"),
        Word(english: "promote", korean: "(동) 촉진하다 / (동) 승진시키다"),
        Word(english: "revenue", korean: "(명) 수익, 수입 / (명) 세입"),
        Word(english: "opportunity", korean: "(명) 기회 / (명) 적기, 호기"),
        Word(english: "valid", korean: "(형) 유효한 / (형) 타당한"),
        Word(english: "confidential", korean: "(형) 기밀의, 비밀의 / (형) 신뢰를 요하는"),
        Word(english: "figure", korean: "(명) 숫자 / (명) 인물"),
        Word(english: "traffic", korean: "(명) 교통, 차량의 흐름 / (명) 인터넷 트래픽, 데이터 흐름"),
        Word(english: "audience", korean: "(명) 청중, 관객 / (명) 독자"),
        Word(english: "occupy", korean: "(동) 공간을 차지하다 / (동) 시간이나 주의를 차지하 다"),
        Word(english: "approximately", korean: "(부) 대략 / (부) 거의"),
        Word(english: "complimentary", korean: "(형) 무료의 / (형) 칭찬의"),
        Word(english: "outstanding", korean: "(형) 미해결의, 미지불된 / (형) 뛰어난, 두드러진"),
        Word(english: "imperative", korean: "(형) 긴급한, 필수적인 / (명) 긴급한 문제, 필수적인 것"),
        Word(english: "substantial", korean: "(형) 상당한 / (형) 실질적인, 실제의"),
        Word(english: "decline", korean: "(동) 감소하다 / (동) 거절하다"),
        Word(english: "balance", korean: "(명) 균형 / (명) 잔액"),
        Word(english: "account", korean: "(명) 계좌 / (명) 설명, 설명서"),
        Word(english: "proceed", korean: "(동) 계속하다, 진행하다 / (동) 시작하다"),
        Word(english: "amenities", korean: "(명) 편의시설 / (명) 예의, 기품"),
        Word(english: "renowned", korean: "(형) 유명한"),
        Word(english: "preserve", korean: "(동) 보존하다 / (명) 저장식품"),
        Word(english: "simply", korean: "(부) 단순하게, 간결하게 / (부) 그저, 단지"),
        Word(english: "presence", korean: "(명) 존재, 출석 / (명) 풍모, 영향력"),
        Word(english: "laboratory", korean: "(명) 실험실"),
        Word(english: "effective", korean: "(형) 효과적인 / (형) 효력을 발휘하는"),
        Word(english: "enhance", korean: "(동) 향상시키다 / (동) 강화하다"),
        Word(english: "insurance", korean: "(명) 보험"),
        Word(english: "spacious", korean: "(형) 넓은, 공간이 많은 / (형) 마음이 넓은, 너그러운"),
        Word(english: "ingredient", korean: "(명) (요리 및 화학 물질의) 재료, 성분 / (명) (성공 등의) 요소"),
        Word(english: "withdraw", korean: "(동) 철회하다 / (동) 철수하다"),
        Word(english: "banquet", korean: "(명) 연회, 만찬 / (명) 성대한 식사"),
        Word(english: "experiment", korean: "(명) 실험 / (동) 실험하다"),
        Word(english: "specific", korean: "(형) 구체적인, 명확한 / (형) 특정한"),
        Word(english: "specialize", korean: "(동) 전문화하다"),
        Word(english: "affect", korean: "(동) 영향을 미치다 / (명) 정서, 감정 (주로 심리학 에서 사용됨)"),
        Word(english: "equip", korean: "(동) 장비를 제공하다 / (동) 준비시키다"),
        Word(english: "reimbursement", korean: "(명) 환급, 상환 / (명) 보상"),
        Word(english: "premises", korean: "(명) 건물과 토지, 부지 / (명) 구내"),
        Word(english: "renovate", korean: "(동) 수리하다, 개조하다"),
        Word(english: "versatile", korean: "(형) 다재다능한 / (형) 다용도의"),
        Word(english: "implement", korean: "(동) 실행하다 / (명) 도구, 장치"),
        Word(english: "informed", korean: "(형) 정보에 기반한"),
        Word(english: "commitment", korean: "(명) 약속 / (명) 헌신"),
        Word(english: "direct", korean: "(형) 직접적인 / (동) 명령하다, 지시하다"),
        Word(english: "facilitate", korean: "(동) 용이하게 하다, 촉진 하다"),
        Word(english: "commission", korean: "(명) 수수료 / (명) 위원회"),
        Word(english: "cover", korean: "(동) 덮다 / (동) 포함하다"),
        Word(english: "encourage", korean: "(동) 격려하다 / (동) 촉진하다"),
        Word(english: "persuade", korean: "(동) 설득하다 / (동) 납득시키다"),
        Word(english: "accompany", korean: "(동) 동반하다, 함께 가다 / (동) 수반하다, 동반하다"),
        Word(english: "candidate", korean: "(명) 후보자, 지원자 / (명) 시험응시자"),
        Word(english: "renew", korean: "(동) 갱신하다 / (동) 재개하다"),
        Word(english: "launch", korean: "(동) 출시하다 / (동) 시작하다"),
        Word(english: "reliable", korean: "(형) 믿을 수 있는, 신뢰할 수 있는 / (명) 신뢰성, 확실성"),
        Word(english: "inform", korean: "(동) 알리다 / (동) 정보 제공하다"),
        Word(english: "contribute", korean: "(동) 기여하다 / (동) 기부하다"),
        Word(english: "strategy", korean: "(명) 전략 / (명) 전술, 방법"),
        Word(english: "motivate", korean: "(동) 동기부여하다 / (동) 유도하다, 자극하다"),
        Word(english: "consider", korean: "(동) 고려하다 / (동) ~라고 여기다"),
        Word(english: "remind", korean: "(동) 상기시키다 / (동) 떠올리게 하다"),
        Word(english: "suitable", korean: "(형) 적합한, 알맞은 / (형) 어울리는"),
        Word(english: "beverage", korean: "(명) 음료"),
        Word(english: "portable", korean: "(형) 휴대할 수 있는 / (명) 휴대용 기기"),
        Word(english: "essential", korean: "(형) 필수적인 / (명) 필수 요소"),
        Word(english: "consent", korean: "(명) 동의, 허락 / (동) 동의하다, 허락하다"),
        Word(english: "tentative", korean: "(형) 잠정적인, 임시의 / (형) 시도적인, 시험적인"),
        Word(english: "respective", korean: "(형) 각각의, 각자의 / (부) 각각, 따로따로"),
        Word(english: "arrange", korean: "(동) 정리하다 / (동) 준비하다"),
        Word(english: "associate", korean: "(동) 관련시키다, 연관짓다 / (동) (사람과) 어울리다, 교제 하다"),
        Word(english: "publicity", korean: "(명) 언론 보도, 광고 / (명) 선전, 홍보"),
        Word(english: "instructor", korean: "(명) 강사, 교관"),
        Word(english: "contractor", korean: "(명) 계약자, 도급업자"),
        Word(english: "relevant", korean: "(형) 관련 있는 / (형) 적절한"),
        Word(english: "weekly", korean: "(형) 매주 열리는 / (부) 매주"),
        Word(english: "imply", korean: "(동) 암시하다"),
        Word(english: "reveal", korean: "(동) 드러내다, 폭로하다 / (동) 보여주다, 나타내다"),
        Word(english: "assembly", korean: "(명) 조립 / (명) 집회, 회의"),
        Word(english: "procedure", korean: "(명) 절차, 과정 / (명) 수술, 의료 절차"),
        Word(english: "overdue", korean: "(형) 기한이 지난 / (형) 연체된"),
        Word(english: "merchandise", korean: "(명) 상품, 물품 / (동) 판매하다, 홍보하다"),
        Word(english: "authority", korean: "(명) 권한 / (명) 당국"),
        Word(english: "fiscal", korean: "(형) 재정의, 회계의"),
        Word(english: "timely", korean: "(형) 시기적절한 / (부) 시기적절하게"),
        Word(english: "duty", korean: "(명) 책임, 의무 / (명) 관세, 세금"),
        Word(english: "impose", korean: "(동) (세금, 규제 등을) 부 과하다 / (동) 강요하다, 강제하다"),
        Word(english: "merger", korean: "(명) 합병 / (명) 융합"),
        Word(english: "demonstration", korean: "(명) 증명, 시연 / (명) 시위"),
        Word(english: "fluctuate", korean: "(동) 변동하다"),
        Word(english: "deliver", korean: "(동) 배달하다, 전달하다 / (동) 연설하다, 발표하다"),
        Word(english: "devoted", korean: "(형) 헌신적인, 열정적인 / (형) 사랑하는"),
        Word(english: "stock", korean: "(명) 재고 / (명) 주식"),
        Word(english: "promptly", korean: "(부) 지체 없이, 즉시 / (부) 정확히"),
        Word(english: "expand", korean: "(동) 확장하다 / (동) 팽창하다"),
        Word(english: "variety", korean: "(명) 다양성, 여러 가지 종 류 / (명) 품종, 종"),
        Word(english: "immediately", korean: "(부) 즉시, 곧"),
        Word(english: "capacity", korean: "(명) 수용 능력, 용량 / (명) 역할, 지위"),
        Word(english: "conduct", korean: "(동) 수행하다 / (동) 지휘하다"),
        Word(english: "transaction", korean: "(명) 거래 / (명) 처리"),
        Word(english: "personnel", korean: "(명) 직원, 인원 / (명) 인사부서"),
        Word(english: "due", korean: "(형) 기한이 된 / (형) 적절한, 맞는"),
        Word(english: "assure", korean: "(동) 안심시키다 / (동) 보증하다, 확언하다"),
        Word(english: "responsibility", korean: "(명) 책임, 의무 / (명) 담당, 역할"),
        Word(english: "progress", korean: "(명) 발전, 진전 / (동) 진보하다, 나아가다"),
        Word(english: "supply", korean: "(명) 공급, 비축품 / (동) 제공하다, 공급하다"),
        Word(english: "release", korean: "(동) 발표하다, 공개하다 / (동) 석방하다, 자유롭게 하다"),
        Word(english: "receipt", korean: "(명) 수령, 영수증 / (명) 영수증을 받음"),
        Word(english: "refuse", korean: "(동) 거절하다 / (명) 폐기물, 쓰레기"),
        Word(english: "prosperous", korean: "(형) 번영하는 / (부) 번영하게, 번창하게"),
        Word(english: "lean", korean: "(동) 기대다 / (동) 기울이다"),
        Word(english: "pedestrian", korean: "(명) 보행자 / (형) 평범한, 재미없는"),
        Word(english: "tenant", korean: "(명) 임차인, 세입자"),
        Word(english: "flaw", korean: "(명) 결함, 흠 / (동) 결함을 만들다"),
        Word(english: "guarantee", korean: "(명) 보증, 보장 / (동) 보장하다, 확실히 하다"),
        Word(english: "loan", korean: "(명) 대출, 차용금 / (동) 빌려주다, 대출하다"),
        Word(english: "admit", korean: "(동) (사실이나 잘못을) 인 정하다 / (동) 입장을 허용하다"),
        Word(english: "expense", korean: "(명) 비용 / (명) 지출"),
        Word(english: "description", korean: "(명) 묘사, 설명"),
        Word(english: "statement", korean: "(명) 진술, 발표 / (명) 명세서, 서류"),
        Word(english: "regulation", korean: "(명) 규제, 규정 / (형) 규제적인"),
        Word(english: "material", korean: "(명) 재료, 물질 / (명) 자료, 정보"),
        Word(english: "policy", korean: "(명) 정책, 방침 / (명) 보험 증권"),
        Word(english: "assume", korean: "(동) 가정하다 / (동) 맡다"),
        Word(english: "critical", korean: "(형) 중요한, 중대한 / (형) 위기의, 위험한"),
        Word(english: "alleviate", korean: "(동) 완화하다, 덜어주다"),
        Word(english: "solicit", korean: "(동) 요청하다, 간청하다 / (동) 청구하다"),
        Word(english: "unprecedented", korean: "(형) 전례 없는"),
        Word(english: "produce", korean: "(동) 생산하다 / (명) 농산물"),
        Word(english: "amount", korean: "(명) 양, 총액 / (동) (합계가) ~에 이르다"),
        Word(english: "commute", korean: "(동) 출퇴근하다 / (동) 통근 시간을 줄이다"),
        Word(english: "corporate", korean: "(형) 기업의, 법인의 / (형) 공동의, 단체의"),
        Word(english: "practical", korean: "(형) 실용적인 / (형) 실제적인, 현실적인"),
        Word(english: "deny", korean: "(동) 부인하다, 사실이 아 니라고 주장하다 / (동) 거부하다, 허락하지 않다"),
        Word(english: "diverse", korean: "(형) 다양한, 여러 가지의"),
        Word(english: "fulfill", korean: "(동) 요구를 충족시키다 / (동) 약속을 완수하다"),
        Word(english: "clarify", korean: "(동) 명확하게 하다 / (동) 분명하게 하다"),
        Word(english: "draft", korean: "(명) 초안, 초고 / (명) 징병, 선발"),
        Word(english: "recipe", korean: "(명) 요리법, 조리법 / (명) 지침, 비법"),
        Word(english: "performance", korean: "(명) 성과 / (명) 공연"),
        Word(english: "invoice", korean: "(명) 청구서 / (동) 청구서를 보내다"),
        Word(english: "useful", korean: "(형) 유용한 / (형) 쓸모있는"),
        Word(english: "durable", korean: "(형) 오래 지속되는, 견고 한"),
        Word(english: "subscribe", korean: "(동) 정기 구독을 신청하 다 / (동) (서비스에) 가입하다"),
        Word(english: "coverage", korean: "(명) 보상 범위 / (명) 보도 범위"),
        Word(english: "approve", korean: "(동) 승인하다 / (동) 찬성하다"),
        Word(english: "agenda", korean: "(명) 의제, 일정 / (명) 할 일 목록"),
        Word(english: "boost", korean: "(동) 증가시키다, 증대하다 / (명) 증가, 증대"),
        Word(english: "access", korean: "(명) 접근, 이용 권한 / (동) 접근하다, 이용하다"),
        Word(english: "facility", korean: "(명) 시설 / (명) 쉬움, 유창함"),
        Word(english: "diagnosis", korean: "(명) 진단 / (명) 문제 분석, 식별"),
        Word(english: "ownership", korean: "(명) 소유권 / (명) 책임"),
        Word(english: "recession", korean: "(명) 불경기, 경기 침체"),
        Word(english: "status", korean: "(명) 상태 / (명) 지위"),
        Word(english: "accountable", korean: "(형) 책임 있는"),
        Word(english: "dependable", korean: "(형) 신뢰할 수 있는"),
        Word(english: "adjustment", korean: "(명) 조정 / (명) 적응"),
        Word(english: "prestigious", korean: "(형) 명망 있는, 존경받는"),
        Word(english: "recognition", korean: "(명) 인정, 승인 / (명) 알아보기, 인식"),
        Word(english: "regret", korean: "(동) 후회하다 / (동) 유감스럽게 생각하다"),
        Word(english: "unemployment", korean: "(명) 실업 / (명) 실업률"),
        Word(english: "documentation", korean: "(명) 문서 작성, 기록 / (명) 증거 자료, 서류"),
        Word(english: "compete", korean: "(동) 경쟁하다"),
        Word(english: "range", korean: "(명) 범위 / (동) (범위가) ~에 이르다"),
        Word(english: "conclusion", korean: "(명) 결론 / (명) 종결"),
        Word(english: "environment", korean: "(명) 자연환경 / (명) 생활환경, 분위기"),
        Word(english: "expose", korean: "(동) 드러내다, 폭로하다 / (동) 노출시키다"),
        Word(english: "appropriate", korean: "(형) 적절한 / (동) 도용하다, 사용하다"),
        Word(english: "negotiate", korean: "(동) 협상하다 / (동) 교섭하다"),
        Word(english: "investment", korean: "(명) 투자 / (명) 투자금, 투자액"),
        Word(english: "productivity", korean: "(명) 생산성"),
        Word(english: "proposal", korean: "(동) 제안하다 / (동) 청혼하다"),
        Word(english: "manual", korean: "(형) 손으로 작동하는, 수 동의 / (명) 주석서, 안내서"),
        Word(english: "potential", korean: "(명) 잠재력, 가능성 / (형) 잠재적인, 가능성이 있는"),
        Word(english: "delay", korean: "(명) 지연 / (동) 연기하다"),
        Word(english: "obtain", korean: "(동) 얻다, 획득하다 / (동) 확보하다"),
        Word(english: "restrict", korean: "(동) 제한하다 / (동) 통제하다"),
        Word(english: "alternative", korean: "(명) 대안, 선택 가능한 것 / (형) 대체의, 대안적인"),
        Word(english: "appraisal", korean: "(명) 평가 / (명) 감정"),
        Word(english: "temporarily", korean: "(부) 일시적으로 / (부) 잠시 동안"),
        Word(english: "remain", korean: "(동) 어떤 상태를 유지하 다 / (동) 남아 있다"),
        Word(english: "relieve", korean: "(동) 고통이나 스트레스를 덜어주다. / (동) 업무에서 해방시키다."),
        Word(english: "beneficial", korean: "(형) 이익이 되는"),
        Word(english: "deliver", korean: "(동) 배송하다 / (동) 연설하다"),
        Word(english: "expect", korean: "(동) 예상하다, 기대하다 / (동) 요구하다, 요청하다"),
        Word(english: "damage", korean: "(명) 손상, 피해 / (동) 손상시키다, 피해를 입히 다"),
        Word(english: "seal", korean: "(동) 봉인하다 / (동) 보증하다"),
        Word(english: "stagnant", korean: "(형) 정체된, 흐르지 않는"),
        Word(english: "tenure", korean: "(명) 재임 기간, 임기 / (명) 종신 재직권, 보유"),
        Word(english: "setback", korean: "(명) 방해, 좌절 / (명) 후퇴"),
        Word(english: "autograph", korean: "(명) 사인 / (동) 사인하다"),
        Word(english: "associated", korean: "(형) 관련된 / (동) 연관시키다, 관련 짓다"),
        Word(english: "arrival", korean: "(명) 도착 / (명) 신생, 도래"),
        Word(english: "dimension", korean: "(명) 크기, 치수 / (명) 양상, 측면"),
        Word(english: "consistency", korean: "(명) 일관성 / (명) (액체의) 농도, 밀도"),
        Word(english: "invent", korean: "(동) 발명하다 / (동) 고안하다, 만들어내다"),
        Word(english: "generous", korean: "(형) 관대한 / (형) 풍부한, 넉넉한"),
        Word(english: "enrich", korean: "(동) 풍요롭게 하다 / (동) (영양소나 성분을) 강화 하다, 높이다"),
        Word(english: "transfer", korean: "(동) 이동하다 / (동) 전근하다"),
        Word(english: "structure", korean: "(명) 구조 / (동) 구조를 설계하다"),
        Word(english: "employment", korean: "(명) 고용, 직업 / (명) 고용률"),
        Word(english: "destination", korean: "(명) 목적지"),
        Word(english: "complaint", korean: "(명) 불평, 불만 / (명) 고충, 문제점"),
        Word(english: "atmosphere", korean: "(명) 분위기, 감정 / (명) 대기, 공기층"),
        Word(english: "host", korean: "(명) 주최자, 주인 / (명) 호스트 컴퓨터"),
        Word(english: "conduct", korean: "(동) 실행하다, 수행하다 / (동) 지휘하다"),
        Word(english: "district", korean: "(명) 구역, 지역"),
        Word(english: "run", korean: "(동) 달리다 / (동) 운영하다"),
        Word(english: "projection", korean: "(명) 예상, 추정 / (명) 영사, 투사"),
        Word(english: "taste", korean: "(명) 맛, 풍미 / (동) 맛보다"),
        Word(english: "transportation", korean: "(명) 교통수단 / (명) 운송"),
        Word(english: "inspiration", korean: "(명) 영감, 동기부여 / (명) 신선한 아이디어나 방안"),
        Word(english: "adequate", korean: "(형) 충분한, 적절한 / (형) 적합한"),
        Word(english: "reputation", korean: "(명) 평판, 명성"),
        Word(english: "rebate", korean: "(명) 환급금 / (동) 환급하다"),
        Word(english: "pension", korean: "(명) 연금 / (명) (유럽 등) 저렴한 호텔"),
        Word(english: "payment", korean: "(명) 지불, 지급 / (명) 청구 금액"),
        Word(english: "permit", korean: "(동) 허가하다, 허용하다 / (명) 허가증, 허가"),
        Word(english: "reservation", korean: "(명) 예약 / (명) 거리낌, 의구심"),
        Word(english: "correspondence", korean: "(명) 서신 왕래 / (명) 편지, 서한"),
        Word(english: "escort", korean: "(명) 동반자, 안내자 / (동) 동행하다, 호위하다"),
        Word(english: "attire", korean: "(명) 의복, 옷차림"),
        Word(english: "inclement", korean: "(형) (날씨가) 궂은"),
        Word(english: "scrutinize", korean: "(동) 면밀히 검토하다"),
        Word(english: "exclusively", korean: "(부) 단독으로, 오로지"),
        Word(english: "collaborate", korean: "(동) 협력하다 / (동) 공동으로 작업하다"),
        Word(english: "consistently", korean: "(부) 일관되게"),
        Word(english: "commensurate", korean: "(형) 상응하는, 비례하는 / (형) 상당하는"),
        Word(english: "streamline", korean: "(동) 간소화하다, 효율화하 다 / (형) 간소화된, 능률적인"),
        Word(english: "freshness", korean: "(명) 신선함 / (명) 새로움"),
        Word(english: "endangered", korean: "(형) 멸종 위기에 처한"),
        Word(english: "aware", korean: "(형) 알고 있는, 인식하고 있는 / (형) 깨닫고 있는, 눈치채고 있는"),
        Word(english: "convert", korean: "(동) 변환하다 / (동) 개종하다, 신념을 바꾸다"),
        Word(english: "contribute", korean: "(동) 기여하다 / (동) 기부하다"),
        Word(english: "fatigue", korean: "(명) 피로 / (동) 피곤하게 하다"),
        Word(english: "advance", korean: "(명) 진전 / (명) 선불"),
        Word(english: "alternative", korean: "(명) 대안 / (형) 대안의"),
        Word(english: "endeavor", korean: "(명) 노력, 시도 / (동) 노력하다, 시도하다"),
        Word(english: "confidence", korean: "(명) 자신감 / (명) 신뢰"),
        Word(english: "symptom", korean: "(명) 증상, 징후"),
        Word(english: "yield", korean: "(동) 생산하다 / (동) 양보하다"),
        Word(english: "nutrition", korean: "(명) 영양"),
        Word(english: "bounce", korean: "(동) 튀어 오르다 / (동) 되돌아오다, 회복하다"),
        Word(english: "curb", korean: "(동) 억제하다, 제한하다 / (명) 억제, 제한"),
        Word(english: "delinquent", korean: "(형) 연체된, 체납된 / (형) 불량한, 비행의"),
        Word(english: "terminate", korean: "(동) 끝내다 / (동) 해고하다"),
        Word(english: "plummet", korean: "(동) 급락하다 / (명) 급락"),
        Word(english: "complication", korean: "(명) 복잡한 문제, 어려움 / (명) 합병증"),
        Word(english: "consensus", korean: "(명) 의견 일치 / (명) 합의"),
        Word(english: "surplus", korean: "(명) 잉여, 과잉 / (형) 남는, 과잉의"),
        Word(english: "remedy", korean: "(명) 치료법, 해결책 / (동) 개선하다, 해결하다"),
        Word(english: "payable", korean: "(형) 지불해야 하는 / (명) 지불해야 할 금액"),
        Word(english: "utilize", korean: "(동) 활용하다 / (동) (기회를) 활용하다"),
        Word(english: "superb", korean: "(형) 탁월한, 뛰어난"),
        Word(english: "demolish", korean: "(동) 철거하다, 파괴하다 / (동) 논리적으로 반박하다, 무 너뜨리다"),
        Word(english: "chronic", korean: "(형) 만성적인"),
        Word(english: "periodically", korean: "(부) 정기적으로"),
        Word(english: "predecessor", korean: "(명) 선임자 / (명) 이전의 것, 전신"),
        Word(english: "markedly", korean: "(부) 두드러지게"),
        Word(english: "precaution", korean: "(명) 예방 조치"),
        Word(english: "discontinue", korean: "(동) 중단하다 / (동) 종료하다"),
        Word(english: "exquisite", korean: "(형) 매우 아름다운, 섬세 한 / (형) 정교한, 세밀한"),
        Word(english: "bulk", korean: "(명) 대량 / (명) 대부분"),
        Word(english: "disruption", korean: "(명) 방해, 중단, 혼란"),
        Word(english: "elegant", korean: "(형) 우아한, 품격 있는 / (명) 우아함, 품격"),
        Word(english: "assorted", korean: "(형) 다양한, 여러 가지 종 류의"),
        Word(english: "stage", korean: "(명) 단계 / (명) 무대"),
        Word(english: "deduct", korean: "(동) 공제하다, 차감하다 / (동) 감액하다"),
        Word(english: "counterfeit", korean: "(명) 위조품, 가짜 / (형) 위조된, 가짜의"),
        Word(english: "perishable", korean: "(형) 쉽게 상할 수 있는 / (명) 부패하기 쉬운 식품"),
        Word(english: "physician", korean: "(명) 의사 / (명) 내과 의사"),
        Word(english: "attentive", korean: "(형) 주의 깊은 / (형) 세심한, 친절한"),
        Word(english: "suburb", korean: "(명) 교외, 외곽 주거지"),
        Word(english: "significant", korean: "(형) 중요한 / (형) 상당한"),
        Word(english: "attempt", korean: "(명) 시도, 노력 / (동) 시도하다, 노력하다"),
        Word(english: "landscape", korean: "(명) 풍경, 경치 / (명) 지역 또는 영역"),
        Word(english: "steadily", korean: "(부) 꾸준하게 / (부) 착실하게"),
        Word(english: "notice", korean: "(명) 공지 / (명) 주목, 인지"),
        Word(english: "applicant", korean: "(명) 지원자 / (명) 신청자"),
        Word(english: "process", korean: "(명) 절차, 과정 / (동) 처리하다"),
        Word(english: "foundation", korean: "(명) 기초, 토대 / (명) 재단, 기금"),
        Word(english: "celebrity", korean: "(명) 유명인사 / (명) 유명세, 명성"),
        Word(english: "accountant", korean: "(명) 회계사"),
        Word(english: "donate", korean: "(동) 기부하다 / (동) 기증하다"),
        Word(english: "inconvenience", korean: "(명) 불편 / (동) 불편을 끼치다"),
        Word(english: "notify", korean: "(동) 알리다, 통지하다"),
        Word(english: "unusually", korean: "(부) 일반적이지 않게, 평 소보다 더"),
        Word(english: "improve", korean: "(동) 개선하다, 향상시키다 / (동) 나아지다, 좋아지다"),
        Word(english: "repair", korean: "(동) 수리하다 / (명) 수리"),
        Word(english: "warranty", korean: "(명) 품질보증서 / (명) 보증 기간"),
        Word(english: "replace", korean: "(동) 대체하다 / (동) 교체하다"),
        Word(english: "production", korean: "(명) 생산, 제작 / (명) 생산량"),
        Word(english: "subscription", korean: "(명) 구독, 가입 / (명) 정기결제"),
        Word(english: "rush", korean: "(명) 급함, 서두름 / (동) 서두르다, 급히 가다"),
        Word(english: "community", korean: "(명) 공동체, 지역 사회"),
        Word(english: "operate", korean: "(동) 기계를 작동시키다 / (동) 사업을 운영하다"),
        Word(english: "fit", korean: "(형) 적합한, 알맞은 / (동) 꼭 맞다"),
        Word(english: "acquire", korean: "(동) 얻다, 획득하다 / (동) 습득하다"),
        Word(english: "confirm", korean: "(동) 확인하다, 확증하다 / (동) 승인하다, 허가하다"),
        Word(english: "attention", korean: "(명) 주의, 집중"),
        Word(english: "concern", korean: "(명) 우려, 걱정 / (동) 관련되다"),
        Word(english: "interest", korean: "(명) 관심 / (명) 이자"),
        Word(english: "purchase", korean: "(명) 구매, 구입 / (동) 구매하다, 구입하다"),
        Word(english: "defective", korean: "(형) 결함이 있는"),
        Word(english: "financial", korean: "(형) 재정의, 금전적인"),
        Word(english: "compliance", korean: "(명) 준수, 따름 / (명) 순응, 따름"),
        Word(english: "lead", korean: "(동) 이끌다, 인도하다 / (동) (어떤 결과로) 이어지다"),
        Word(english: "organize", korean: "(동) 정리하다 / (동) 체계를 세우다"),
        Word(english: "mistakenly", korean: "(부) 실수로, 잘못하여"),
        Word(english: "attract", korean: "(동) 끌어당기다 / (동) 유발하다, 유인하다"),
        Word(english: "depart", korean: "(동) 출발하다 / (동) 떠나다"),
        Word(english: "donation", korean: "(명) 기부"),
        Word(english: "summary", korean: "(동) 정보를 제공하다, 알 리다"),
        Word(english: "awareness", korean: "(명) 인식, 의식 / (명) 자각, 알고 있음"),
        Word(english: "harvest", korean: "(명) 수확물 / (동) 수확하다"),
        Word(english: "plumber", korean: "(명) 배관공"),
        Word(english: "review", korean: "(명) 검토, 평가 / (동) 검토하다, 재검토하다"),
        Word(english: "consumer", korean: "(명) 소비자"),
        Word(english: "describe", korean: "(동) 묘사하다, 설명하다 / (동) 나타내다, 정의하다"),
        Word(english: "provide", korean: "(동) 제공하다 / (동) 준비하다, 마련하다"),
        Word(english: "convenience", korean: "(명) 편리함, 편리한 것 / (명) 편의 시설"),
        Word(english: "aim", korean: "(명) 목표 / (동) 겨냥하다"),
        Word(english: "prospective", korean: "(형) 장래의, 예비의 / (형) 가망 있는, 가능성이 높 은"),
        Word(english: "exceptional", korean: "(형) 뛰어난, 특출한 / (형) 예외적인, 이례적인"),
        Word(english: "result", korean: "(명) 결과 / (동) 결과로서 발생하다"),
        Word(english: "advantage", korean: "(명) 장점, 유리한 점 / (동) 유리하게 하다"),
        Word(english: "satisfaction", korean: "(명) 만족감 / (명) 보상, 보답"),
        Word(english: "dedicated", korean: "(형) 헌신적인, 전념하는 / (형) 특정 목적을 위한"),
        Word(english: "emphasis", korean: "(명) 강조 / (명) 중점"),
        Word(english: "labor", korean: "(명) 노동, 일 / (동) 노동하다, 힘쓰다"),
        Word(english: "foster", korean: "(동) 발전시키다, 육성하다 / (동) 양육하다, 돌보다"),
        Word(english: "demand", korean: "(명) 수요 / (동) 요구하다"),
        Word(english: "selection", korean: "(명) 선택된 것, 선발된 사 람 / (명) 선택 과정, 선발 과정"),
        Word(english: "conscious", korean: "(형) 의식하는, 자각하는 / (형) 의식이 있는"),
        Word(english: "efficiently", korean: "(부) 효율적으로 / (부) 효과적으로"),
        Word(english: "comparable", korean: "(형) 비교할 만한 / (형) 유사한"),
        Word(english: "corrosion", korean: "(명) 부식 / (명) (비유적) 점차적인 손상"),
        Word(english: "personal", korean: "(형) 개인적인 / (형) 사적인"),
        Word(english: "popular", korean: "(형) 인기 있는 / (형) 대중의"),
        Word(english: "influence", korean: "(명) 영향 / (동) 영향을 미치다"),
        Word(english: "dramatic", korean: "(형) 극적인, 급격한 / (형) 인상적인, 감정을 자극하 는"),
        Word(english: "aid", korean: "(명) 도움, 지원 / (동) 돕다, 지원하다"),
        Word(english: "fascinating", korean: "(형) 매혹적인"),
        Word(english: "concentrate", korean: "(동) 집중하다 / (동) (사람이나 물자를) 모으 다"),
        Word(english: "lecture", korean: "(명) 강의, 강연 / (동) 강의하다, 연설하다"),
        Word(english: "ideal", korean: "(형) 이상적인 / (형) 최적의"),
        Word(english: "worth", korean: "(형) ~의 가치가 있는 / (명) 가치"),
        Word(english: "value", korean: "(명) 가치, 중요성 / (동) 평가하다, 존중하다"),
        Word(english: "introduce", korean: "(동) 도입하다 / (동) 소개하다"),
        Word(english: "attend", korean: "(동) 참석하다 / (동) 돌보다"),
        Word(english: "method", korean: "(명) 방법, 방식 / (명) 체계, 체계성"),
        Word(english: "permanent", korean: "(형) 영구적인, 지속적인 / (형) 계속되는, 변하지 않는"),
        Word(english: "recovery", korean: "(명) 회복 / (명) 복구"),
        Word(english: "object", korean: "(명) 물건, 사물 / (명) 목적, 목표"),
        Word(english: "attain", korean: "(동) (목표, 수준 등에) 도 달하다 / (동) (나이나 기간을) 맞이하 다"),
        Word(english: "convene", korean: "(동) 소집하다 / (동) 모이다"),
        Word(english: "eliminate", korean: "(동) 제거하다, 없애다 / (동) 탈락시키다"),
        Word(english: "expertise", korean: "(명) 전문 지식, 전문 기술 / (명) 전문가 의견"),
        Word(english: "retain", korean: "(동) 유지하다, 보유하다 / (동) 기억하다"),
        Word(english: "hesitate", korean: "(동) 주저하다, 망설이다 / (동) 망설이며 말하다"),
        Word(english: "schedule", korean: "(명) 일정, 시간표 / (동) 일정을 잡다, 계획하다"),
        Word(english: "project", korean: "(명) 프로젝트, 계획 / (동) 예상하다, 예측하다"),
        Word(english: "credit", korean: "(명) 신용, 신뢰 / (명) 입금, 잔액"),
        Word(english: "accrue", korean: "(동) 증가하다, 축적되다"),
        Word(english: "dig", korean: "(동) 땅을 파다 / (동) 정보를 찾다"),
        Word(english: "remit", korean: "(동) 송금하다 / (동) 면제하다"),
        Word(english: "favorable", korean: "(형) 호의적인 / (형) 유리한"),
        Word(english: "state", korean: "(명) 상태 / (명) 주, 국가"),
        Word(english: "patio", korean: "(명) 파티오, 테라스 / (명) 외부 휴식 공간"),
        Word(english: "recreational", korean: "(형) 여가의, 오락의"),
        Word(english: "valley", korean: "(명) 계곡, 골짜기"),
        Word(english: "skeptical", korean: "(형) 의심 많은"),
        Word(english: "positive", korean: "(형) 긍정적인 / (형) 확신하는"),
        Word(english: "economy", korean: "(명) 경제 / (명) 절약, 경제성"),
        Word(english: "propose", korean: "(동) 제안하다 / (동) 청혼하다"),
        Word(english: "debut", korean: "(명) 첫 등장, 데뷔 / (동) 첫선을 보이다, 데뷔하다"),
        Word(english: "fire", korean: "(명) 불, 화재 / (동) 해고하다"),
        Word(english: "hire", korean: "(동) 고용하다 / (동) 임대하다"),
        Word(english: "attitude", korean: "(명) 태도, 마음가짐 / (명) 입장, 견해"),
        Word(english: "region", korean: "(명) 지역, 구역 / (명) 분야, 영역"),
        Word(english: "dispose", korean: "(동) 처리하다, 처분하다 / (동) 배치하다"),
        Word(english: "divide", korean: "(동) 나누다, 분할하다 / (동) 갈라놓다, 분열시키다"),
        Word(english: "proficiency", korean: "(명) 숙련도 / (명) 능력"),
        Word(english: "managerial", korean: "(형) 경영의, 관리의"),
        Word(english: "growth", korean: "(명) 성장, 발전 / (명) 증가, 증식"),
        Word(english: "independent", korean: "(형) 독립적인 / (형) 자립적인"),
        Word(english: "apologize", korean: "(동) 사과하다"),
        Word(english: "refer", korean: "(동) 언급하다 / (동) 참조하다"),
        Word(english: "follow", korean: "(동) 뒤를 따르다 / (동) 지시나 규칙을 따르다"),
        Word(english: "broad", korean: "(형) 넓은, 광범위한 / (형) 일반적인, 종합적인"),
        Word(english: "diversified", korean: "(형) 다양한, 다각화된 / (diver 다각화하다, 다양화하다"),
        Word(english: "ailing", korean: "(형) 병든, 아픈 / (형) 경제적으로 어려움을 겪 고 있는"),
        Word(english: "occupancy", korean: "(명) 점유, 사용"),
        Word(english: "hospitality", korean: "(명) 환대 / (명) 환대 산업"),
        Word(english: "furnished", korean: "(형) 가구가 비치된 / (형) 가구를 비치하다, 제공하 다"),
        Word(english: "enlightening", korean: "(형) 계몽적인, 유익한 / (동) 계몽하다, 설명하다"),
        Word(english: "municipal", korean: "(형) 시의, 지방 자치의"),
        Word(english: "regard", korean: "(동) 간주하다, 여기다 / (동) 관련되다"),
        Word(english: "routinely", korean: "(부) 정기적으로 / (형) 일상적인"),
        Word(english: "overview", korean: "(명) 개요 / (명) 전반적인 설명, 개괄"),
        Word(english: "qualify", korean: "(동) 자격을 얻다 / (동) 적합하다"),
        Word(english: "determine", korean: "(동) 결정하다 / (동) 확정하다, 판별하다"),
        Word(english: "overcharge", korean: "(동) 과다 청구하다 / (동) 과충전하다"),
        Word(english: "keep", korean: "(동) 유지하다 / (동) 보관하다"),
        Word(english: "costume", korean: "(명) 복장, 의상"),
        Word(english: "evenly", korean: "(부) 고르게, 균등하게 / (부) 평평하게"),
        Word(english: "industry", korean: "(명) 산업 / (명) 근면"),
        Word(english: "highlight", korean: "(동) 강조하다 / (명) 가장 중요한 부분, 하이 라이트"),
        Word(english: "journal", korean: "(명) 일기, 기록 / (명) 학술지, 정기간행물"),
        Word(english: "shore", korean: "(명) 해안, 물가 / (동) 지지하다, 강화하다"),
        Word(english: "statue", korean: "(명) 동상, 조각상"),
        Word(english: "astronomy", korean: "(명) 천문학"),
        Word(english: "flexible", korean: "(형) 유연한, 융통성 있는"),
        Word(english: "circulate", korean: "(동) 순환하다 / (동) 배포하다, 퍼뜨리다"),
        Word(english: "merit", korean: "(명) 장점, 가치 / (동) (어떠한 대우를) 받을 만 하다, 가치가 있다"),
        Word(english: "moderate", korean: "(형) 적당한, 중간의 / (동) 완화하다, 조정하다"),
        Word(english: "artificial", korean: "(형) 인공적인 / (형) 부자연스러운"),
        Word(english: "analyze", korean: "(동) 분석하다 / (동) 평가하다"),
        Word(english: "modernize", korean: "(동) 현대화하다 / (동) 개선하다, 개혁하다"),
        Word(english: "operation", korean: "(명) 운영 / (명) 작전"),
        Word(english: "medical", korean: "(형) 의학의, 의료의"),
        Word(english: "block", korean: "(명) 덩어리 / (명) 한 구획"),
        Word(english: "individual", korean: "(명) 개인 / (형) 개별적인, 개인적인"),
        Word(english: "deadline", korean: "(명) 마감일, 기한 / (명) 시한, 시간 제한"),
        Word(english: "wrap", korean: "(동) 포장하다 / (동) 덮다, 감싸다"),
        Word(english: "trial", korean: "(명) 재판 / (명) 시험, 시도"),
        Word(english: "institute", korean: "(명) 기관, 연구소 / (동) 설립하다"),
        Word(english: "cooperation", korean: "(명) 협력 / (명) 협조, 지원"),
        Word(english: "resident", korean: "(명) 거주자 / (명) 수련의"),
        Word(english: "flight", korean: "(명) 비행, 항공 여행 / (명) (계단의) 층, 계단"),
        Word(english: "department", korean: "(명) 부서, 학과 / (명) 소매점의 부문"),
        Word(english: "separate", korean: "(동) 분리하다 / (형) 별개의, 독립된"),
        Word(english: "ladder", korean: "(명) 사다리 / (명) 승진 단계, 출세의 길"),
        Word(english: "passenger", korean: "(명) 승객 / (명) 동승자"),
        Word(english: "closet", korean: "(명) 옷장, 작은 방 / (동) 비밀로 하다, 감추다"),
        Word(english: "rare", korean: "(형) 희귀한, 드문 / (형) 거의 익지 않은 (음식)"),
        Word(english: "masterpiece", korean: "(명) 걸작, 명작 / (명) 최고의 작품"),
        Word(english: "broadcast", korean: "(동) 방송하다 / (명) 방송, 방송 프로그램"),
        Word(english: "retrieve", korean: "(동) 되찾다, 회수하다 / (동) (정보를) 검색하다"),
        Word(english: "replacement", korean: "(명) 대체, 교체 / (명) 후임자, 후임"),
        Word(english: "storage", korean: "(명) 저장, 보관 / (명) 저장소, 창고"),
        Word(english: "hectic", korean: "(형) 매우 바쁜, 정신없이 분주한 / (형) 험난한, 격렬한"),
        Word(english: "vessel", korean: "(명) 배, 선박 / (명) 용기, 그릇"),
        Word(english: "resign", korean: "(동) 사임하다 / (동) 체념하다, 포기하다"),
        Word(english: "load", korean: "(명) 짐, 중량 / (동) 짐을 싣다"),
        Word(english: "supervisor", korean: "(명) 감독자 / (명) 관리인"),
        Word(english: "sculpture", korean: "(명) 조각, 조각 작품 / (동) 조각하다"),
        Word(english: "rent", korean: "(동) 임대하다 / (동) 빌려주다"),
        Word(english: "garage", korean: "(명) 차고 / (명) 자동차 정비소"),
        Word(english: "resource", korean: "(명) 자원 / (명) 재료, 원천"),
        Word(english: "flavor", korean: "(명) 맛, 향 / (명) 특정한 느낌, 분위기"),
        Word(english: "apply", korean: "(동) 지원하다 / (동) 적용하다"),
        Word(english: "rack", korean: "(명) 선반, 짐대 / (동) 고통을 주다, 괴롭히다"),
        Word(english: "acquisition", korean: "(명) 인수 / (명) 획득"),
        Word(english: "commercial", korean: "(형) 상업적인 / (명) 광고"),
        Word(english: "revise", korean: "(동) 수정하다 / (동) 검토하다"),
        Word(english: "outdated", korean: "(형) 구식의, 시대에 뒤떨 어진"),
        Word(english: "private", korean: "(형) 개인적인, 사적인 / (형) 비공개의, 비밀의"),
        Word(english: "tray", korean: "(명) 쟁반, 받침"),
        Word(english: "entrance", korean: "(명) 입구, 진입로 / (명) 입장(진입)"),
        Word(english: "pharmacy", korean: "(명) 약국 / (명) 약학"),
        Word(english: "appeal", korean: "(동) 호소하다 / (동) 항소하다"),
        Word(english: "errand", korean: "(명) 심부름 / (명) 사적인 용무"),
        Word(english: "knob", korean: "(명) 손잡이 / (명) 돌기"),
        Word(english: "compile", korean: "(동) 자료를 모으다, 편집 하다 / (동) (프로그램을) 컴파일하다"),
        Word(english: "composer", korean: "(명) 작곡가"),
        Word(english: "linger", korean: "(동) (장소에) 오래 머무르 다 / (동) (냄새가) 남아 있다"),
        Word(english: "submit", korean: "(동) 제출하다 / (동) 복종하다"),
        Word(english: "abundant", korean: "(형) 풍부한, 많은 / (형) 넘치는"),
        Word(english: "sneeze", korean: "(명) 재채기 / (동) 재채기하다"),
        Word(english: "lease", korean: "(명) 임대 계약 / (동) 임대하다"),
        Word(english: "dine", korean: "(동) 식사하다 / (동) 공식적인 자리에서 식사 하다"),
        Word(english: "priority", korean: "(명) 우선순위 / (명) 긴급히 처리해야 할 사항"),
        Word(english: "nominate", korean: "(동) 후보자로 지명하다 / (동) 임명하다"),
        Word(english: "observe", korean: "(동) 목격하다, 보다 / (동) 준수하다"),
        Word(english: "waste", korean: "(명) 낭비, 쓰레기 / (동) 낭비하다"),
        Word(english: "adjacent", korean: "(형) 인접한, 가까운 / (형) 가까운, 근접한"),
        Word(english: "conflict", korean: "(명) 갈등, 충돌 / (동) 충돌하다, 상충하다"),
        Word(english: "target", korean: "(명) 목표 / (명) 표적, 정조준의 대상"),
        Word(english: "letterhead", korean: "(명) (편지지의) 편지 머리 글 / (명) 회사 이름과 주소가 인쇄 된 편지지"),
        Word(english: "pertinent", korean: "(형) 관련 있는, 적절한"),
        Word(english: "compensation", korean: "(명) 보상, 배상 / (명) 급여, 임금"),
        Word(english: "interview", korean: "(명) 면접 / (동) 인터뷰를 하다, 면접을 보다"),
        Word(english: "retire", korean: "(동) 은퇴하다 / (동) 물러나다, 퇴각하다"),
        Word(english: "collective", korean: "(형) 집단의, 공동의 / (명) 집단, 공동체"),
        Word(english: "annually", korean: "(부) 매년"),
        Word(english: "found", korean: "(동) 설립하다, 창립하다 / (동) 발견했다, 찾았다"),
        Word(english: "discourage", korean: "(동) 단념시키다, 못 하게 하다 / (동) 사기를 꺾다"),
        Word(english: "ticket", korean: "(명) 입장권, 관람권 / (명) 교통 위반 티켓, 벌금 통 지서"),
        Word(english: "inquiry", korean: "(명) 질문, 문의 / (명) 조사, 연구"),
        Word(english: "dominate", korean: "(동) 지배하다 / (동) 우위를 차지하다"),
        Word(english: "signal", korean: "(명) 신호 / (동) 신호를 보내다"),
        Word(english: "allergic", korean: "(형) 알레르기가 있는 / (형) 극도로 싫어하는"),
        Word(english: "view", korean: "(명) 견해, 관점 / (명) 전망, 경치"),
        Word(english: "spicy", korean: "(형) 매운 / (형) 자극적인, 흥미로운"),
        Word(english: "entertain", korean: "(동) 즐겁게 하다 / (동) 접대하다"),
        Word(english: "manuscript", korean: "(명) 원고, 필사본"),
        Word(english: "placement", korean: "(명) 배치, 놓기 / (명) 고용 배치"),
        Word(english: "accumulation", korean: "(명) 축적, 누적"),
        Word(english: "hypothesis", korean: "(명) 가설 / (명) 추정"),
        Word(english: "component", korean: "(명) 구성 요소, 부품 / (명) 성분, 재료"),
        Word(english: "dehydrate", korean: "(동) 수분을 제거하다 / (동) 탈수 상태로 만들다"),
        Word(english: "fever", korean: "(명) 열, 발열 / (명) (비유적으로) 열정, 흥분"),
        Word(english: "vaccinate", korean: "(동) 백신을 접종하다 / (동) ~에 대한 백신을 접종하 다"),
        Word(english: "contagious", korean: "(형) 전염성의 / (형) 영향을 주는"),
        Word(english: "frigid", korean: "(형) 매우 추운 / (형) 냉담한"),
        Word(english: "pollution", korean: "(명) 오염, 공해 / (명) 불법, 범죄"),
        Word(english: "neighborhood", korean: "(명) 이웃, 인근 / (명) 지역사회"),
        Word(english: "exhibit", korean: "(동) 전시하다 / (동) 드러내다, 보이다"),
        Word(english: "turn", korean: "(동) 돌다, 방향을 바꾸다 / (동) 바뀌다, 전환하다"),
        Word(english: "vote", korean: "(명) 투표, 표 / (동) 투표하다"),
        Word(english: "coastal", korean: "(형) 해안의"),
        Word(english: "definitely", korean: "(부) 확실히, 분명히"),
        Word(english: "rest", korean: "(명) 휴식 / (명) 나머지"),
        Word(english: "prefer", korean: "(동) 더 좋아하다, 선호하 다 / (동) 제안하다, 추천하다 (비 교적 덜 일반적)"),
        Word(english: "directory", korean: "(명) 목록, 안내 책자 / (명) 컴퓨터 파일 구조"),
        Word(english: "contain", korean: "(동) 포함하다, 담다 / (동) 억제하다, 통제하다"),
        Word(english: "valuable", korean: "(형) 귀중한, 중요한 / (명) 귀중품"),
        Word(english: "charity", korean: "(명) 자선 단체 / (명) 자선 행위"),
        Word(english: "approach", korean: "(동) 다가가다, 접근하다 / (명) 접근법, 방법"),
        Word(english: "lock", korean: "(동) 잠그다 / (동) 고정시키다"),
        Word(english: "plant", korean: "(명) 식물 / (명) 공장"),
        Word(english: "province", korean: "(명) 주, 지방 / (명) (책임이나 업무의) 분야"),
        Word(english: "decade", korean: "(명) 10년"),
        Word(english: "appreciate", korean: "(동) 감사하다 / (동) 진가를 알아보다"),
        Word(english: "dental", korean: "(형) 치과의, 치아의 / (형) 치과용의"),
        Word(english: "patronage", korean: "(명) 후원, 지원 / (명) 단골, 고객"),
        Word(english: "venue", korean: "(명) 행사 장소 / (명) 법정 관할지"),
        Word(english: "book", korean: "(명) 책 / (동) 예약하다"),
        Word(english: "mechanic", korean: "(명) 기계공, 정비공 / (명) 기술, 방법"),
        Word(english: "fold", korean: "(동) 접다 / (동) 사업이나 활동을 중단하 다"),
        Word(english: "achievement", korean: "(명) 성취, 달성"),
        Word(english: "supplier", korean: "(명) 공급자, 공급업체"),
        Word(english: "conductor", korean: "(명) 지휘자 / (명) 전도체"),
        Word(english: "appointment", korean: "(명) 약속, 예약 / (명) 임명, 지명"),
        Word(english: "contribution", korean: "(명) 기여, 공헌 / (명) 기부금"),
        Word(english: "certain", korean: "(형) 특정한 / (형) 확신하는"),
        Word(english: "personally", korean: "(부) 개인적으로 / (부) 직접적으로"),
        Word(english: "leave", korean: "(동) 떠나다 / (동) 남기다"),
        Word(english: "attachment", korean: "(명) 첨부 파일 / (명) 애착, 정서적 유대"),
        Word(english: "hand", korean: "(명) 손 / (명) 도움"),
        Word(english: "postpone", korean: "(동) 연기하다, 미루다 / (동) 차일피일 미루다"),
        Word(english: "regularly", korean: "(부) 정기적으로"),
        Word(english: "addition", korean: "(명) 추가, 덧셈 / (명) 부가물, 추가 부분"),
        Word(english: "flier", korean: "(명) 광고 전단지 / (명) 항공편 승객"),
        Word(english: "inefficient", korean: "(형) 비효율적인"),
        Word(english: "avoid", korean: "(동) 피하다 / (동) 회피하다"),
        Word(english: "stand", korean: "(동) 서다 / (동) 견디다, 참다"),
        Word(english: "entertainment", korean: "(명) 오락, 여흥 / (명) 연예, 공연"),
        Word(english: "tournament", korean: "(명) 대회, 토너먼트 / (명) 시합"),
        Word(english: "pack", korean: "(동) 짐을 싸다 / (동) 포장하다"),
        Word(english: "reduced", korean: "(형) 감소된, 축소된 / (형) 할인된"),
        Word(english: "retailer", korean: "(명) 소매업자, 소매점"),
        Word(english: "directions", korean: "(명) 지시 / (명) 길 안내"),
        Word(english: "railing", korean: "(명) 난간"),
        Word(english: "belong", korean: "(동) 속하다 / (동) 어울리다, 적합하다"),
        Word(english: "traditional", korean: "(형) 전통적인 / (형) 구식의"),
        Word(english: "electricity", korean: "(명) 전기"),
        Word(english: "injure", korean: "(동) 상처를 입히다, 부상 을 입히다 / (동) 해치다, 손상시키다"),
        Word(english: "patient", korean: "(명) 환자 / (형) 참을성 있는, 인내심 있 는"),
        Word(english: "weed", korean: "(명) 잡초 / (동) 잡초를 제거하다"),
        Word(english: "patience", korean: "(명) 인내심 / (명) 참을성"),
        Word(english: "probably", korean: "(부) 아마도"),
        Word(english: "water", korean: "(명) 물 / (동) 물을 주다"),
        Word(english: "save", korean: "(동) 저축하다 / (동) 구하다"),
        Word(english: "position", korean: "(명) 위치, 자리 / (명) 직위, 일자리"),
        Word(english: "activate", korean: "(동) 작동시키다 / (동) 활성화하다"),
        Word(english: "alteration", korean: "(명) 변경, 수정"),
        Word(english: "artifact", korean: "(명) 인공물, 유물 / (명) 인위적 산물, 부작용"),
        Word(english: "assessment", korean: "(명) 평가 / (명) 검토"),
        Word(english: "flammable", korean: "(형) 가연성의, 불이 붙기 쉬운 / (명) 가연물"),
        Word(english: "integral", korean: "(형) 필수적인 / (형) 완전한"),
        Word(english: "inaugural", korean: "(형) 취임의 / (형) 첫 번째의, 개시의"),
        Word(english: "intensive", korean: "(형) 집중적인 / (형) 강한, 강력한"),
        Word(english: "statistics", korean: "(명) 통계, 통계 자료 / (명) 통계학"),
        Word(english: "overwhelming", korean: "(형) 압도적인, 강력한 / (형) 극도의, 극심한"),
        Word(english: "void", korean: "(명) 빈 공간 / (형) 무효의"),
        Word(english: "tactic", korean: "(명) 전술, 전략, 방법 / (명) 약삭빠르게 사용하는 수 단"),
        Word(english: "heritage", korean: "(명) 문화유산 / (명) 전통"),
        Word(english: "discard", korean: "(동) 버리다 / (동) 없애다, 제거하다"),
        Word(english: "disposable", korean: "(형) 일회용의 / (명) 일회용품"),
        Word(english: "chronicle", korean: "(명) 연대기, 기록 / (동) 기록하다, 연대순으로 이 야기하다"),
        Word(english: "fundraising", korean: "(명) 자금 모금 활동 / (명) 자금 조달"),
        Word(english: "pertain", korean: "(동) 관련되다 / (동) 적용되다"),
        Word(english: "consideration", korean: "(명) 고려 / (명) 배려"),
        Word(english: "distributed", korean: "(형) 분배된, 배포된 / (형) 퍼진, 흩어진"),
        Word(english: "loss", korean: "(명) 손실 / (명) 감량, 감소"),
        Word(english: "experience", korean: "(명) 경험 / (동) 경험하다"),
        Word(english: "local", korean: "(형) 특정 지역의, 현지의 / (명) 지역 주민"),
        Word(english: "predict", korean: "(동) 예측하다"),
        Word(english: "regarding", korean: "(전) 무엇에 관하여"),
        Word(english: "accordingly", korean: "(명) 합의, 일치 / (동) 부여하다"),
        Word(english: "limited", korean: "(형) 제한된, 한정된 / (형) 부족한, 충분하지 않은"),
        Word(english: "expiration", korean: "(명) 만료 / (명) 종료"),
        Word(english: "automated", korean: "(형) 자동화된 / (형) 자동으로 작동하는"),
        Word(english: "enclosed", korean: "(동) 둘러싸다 / (동) 동봉하다"),
        Word(english: "accomplished", korean: "(형) 능숙한, 성취한"),
        Word(english: "stable", korean: "(형) 안정된 / (형) 변하지 않는, 견고한"),
        Word(english: "mutually", korean: "(부) 상호 간에 / (부) 서로 간에"),
        Word(english: "prescription", korean: "(명) 처방전 / (명) 권장 사항"),
        Word(english: "cancellation", korean: "(명) 취소"),
        Word(english: "price", korean: "(명) 가격 / (동) 가격을 매기다"),
        Word(english: "carefully", korean: "(부) 주의 깊게, 신중하게 / (부) 세심하게"),
        Word(english: "foremost", korean: "(형) 가장 중요한 / (형) 선두의, 일류의"),
        Word(english: "generously", korean: "(부) 아낌없이, 관대하게"),
        Word(english: "specialization", korean: "(명) 전문화 / (명) 특수화"),
        Word(english: "preparation", korean: "(명) 준비, 준비 작업 / (명) 대비, 대비책"),
        Word(english: "transition", korean: "(명) 변화, 전환 / (동) 변천하다, 전환하다"),
        Word(english: "productive", korean: "(형) 생산성이 높은 / (형) 결실이 있는, 유익한"),
        Word(english: "unfavorable", korean: "(형) 호의적이지 않은 / (형) 불리한"),
        Word(english: "boardroom", korean: "(명) 이사회 회의실 / (명) 고위 경영 회의 공간"),
        Word(english: "ambitious", korean: "(형) 야심 있는"),
        Word(english: "enlarge", korean: "(동) 크기를 확대하다 / (동) 범위를 확장하다"),
        Word(english: "apparent", korean: "(형) 명백한, 분명한 / (형) 겉보기의, 외관상"),
        Word(english: "briefly", korean: "(부) 잠시 동안 / (부) 간단히"),
        Word(english: "regain", korean: "(동) 되찾다"),
        Word(english: "duplication", korean: "(명) 복제 / (명) 중복"),
        Word(english: "paperwork", korean: "(명) 서류 작업"),
        Word(english: "unanimously", korean: "(부) 만장일치로"),
        Word(english: "general", korean: "(형) 일반적인 / (형) 전체적인"),
        Word(english: "usual", korean: "(형) 보통의, 평소의 / (형) 흔히 있는, 일상적인"),
        Word(english: "advisor", korean: "(동) 기여하다, 공헌하다 / (동) (글이나 기사를) 기고하 다"),
        Word(english: "pretty", korean: "(형) 예쁜, 매력적인 / (부) 꽤, 상당히"),
        Word(english: "suited", korean: "(형) 어울리거나 적합한 / (형) 준비된, 맞춰진"),
        Word(english: "familiarity", korean: "(명) 친숙함, 잘 알고 있음 / (명) 친밀함"),
        Word(english: "seek", korean: "(동) 찾다 / (동) 추구하다"),
        Word(english: "invite", korean: "(동) 초대하다, 요청하다 / (동) 권유하다, 초래하다"),
        Word(english: "independently", korean: "(부) 독립적으로 / (부) 자율적으로"),
        Word(english: "diligent", korean: "(형) 근면한, 성실한"),
        Word(english: "inexperienced", korean: "(형) 경험이 없는, 미숙한"),
        Word(english: "leadership", korean: "(명) 지도력, 리더십"),
        Word(english: "moderately", korean: "(부) 적당히 / (부) 중간 정도로"),
        Word(english: "customized", korean: "(형) 맞춤형의, 개인화된"),
        Word(english: "preferential", korean: "(형) 특혜의 / (형) 우선적인"),
        Word(english: "effectiveness", korean: "(명) 효과적임, 효율성"),
        Word(english: "inexpensive", korean: "(형) 저렴한, 비용이 낮은"),
        Word(english: "sharply", korean: "(부) 급격하게 / (부) 날카롭게"),
        Word(english: "discreetly", korean: "(부) 신중하게"),
        Word(english: "periodic", korean: "(형) 주기적인"),
        Word(english: "exponentially", korean: "(부) 기하급수적으로"),
        Word(english: "outgoing", korean: "(형) 외향적인, 사교적인 / (형) 퇴임하는, 떠나는"),
        Word(english: "welcome", korean: "(동) 환영하다 / (형) 환영받는, 반가운"),
        Word(english: "support", korean: "(동) 지지하다, 지원하다 / (명) 지원"),
        Word(english: "informal", korean: "(형) 격식을 차리지 않는 / (형) 비공식적인"),
        Word(english: "excellence", korean: "(명) 뛰어남, 탁월함"),
        Word(english: "inspiring", korean: "(형) 영감을 주는 / (형) 영감을 받은"),
        Word(english: "acceptable", korean: "(형) 받아들일 수 있는 / (형) 수용 가능한"),
        Word(english: "amendment", korean: "(명) 수정, 변경 / (명) 개정(법률)"),
        Word(english: "breakable", korean: "(형) 파손되기 쉬운"),
        Word(english: "trade", korean: "(명) 무역, 거래 / (동) 교환하다, 거래하다"),
        Word(english: "descending", korean: "(형) 내려가는, 하향의 / (형) 내림차순의"),
        Word(english: "fluctuation", korean: "(명) 변동, 오르내림"),
        Word(english: "lure", korean: "(동) 유혹하다 / (명) 유혹, 매혹"),
        Word(english: "perfectly", korean: "(부) 완벽하게 / (부) 전적으로"),
        Word(english: "utilities", korean: "(명) 공공서비스, 공과금 / (명) 유용성, 유틸리티"),
        Word(english: "loyalty", korean: "(명) 충성, 헌신 / (명) 신뢰, 신의"),
        Word(english: "individually", korean: "(부) 개별적으로 / (부) 각각"),
        Word(english: "shortcoming", korean: "(명) 결점, 단점"),
        Word(english: "unrivaled", korean: "(형) 비할 데 없는, 유일무 이한"),
        Word(english: "accommodations", korean: "(명) 숙박 시설"),
        Word(english: "frozen", korean: "(형) 얼린 / (형) 정지된"),
        Word(english: "stay", korean: "(동) 머무르다, 체재하다 / (동) 계속하다, 유지하다"),
        Word(english: "courtyard", korean: "(명) 안마당, 중정"),
        Word(english: "tourist", korean: "(명) 관광객 / (명) 여행객"),
        Word(english: "canceled", korean: "(형) 취소된 / (동) 취소하다"),
        Word(english: "landmark", korean: "(명) 주요 지형지물 / (명) 중요한 사건, 이정표"),
        Word(english: "frequent", korean: "(동) 자주 방문하다 / (형) 빈번한"),
        Word(english: "nightly", korean: "(형) 매일 밤의, 밤마다의 / (부) 매일 밤"),
        Word(english: "holder", korean: "(명) 소지자, 보유자 / (명) 자, 받침대"),
        Word(english: "resounding", korean: "(형) 울리는, 울려퍼지는 / (형) 압도적인, 확실한"),
        Word(english: "worldwide", korean: "(형) 세계적인 / (부) 전 세계적으로"),
        Word(english: "theatrical", korean: "(형) 연극의, 연극적인"),
        Word(english: "proudly", korean: "(부) 자랑스럽게"),
        Word(english: "theatergoer", korean: "(명) 연극 애호가, 관람객"),
        Word(english: "appraise", korean: "(동) 평가하다 / (동) 감정하다"),
        Word(english: "discretionary", korean: "(형) 자유 재량의"),
        Word(english: "unease", korean: "(명) 불안, 걱정"),
        Word(english: "located", korean: "(형) 위치한 / 분사 위치를 찾다"),
        Word(english: "distinctive", korean: "(형) 독특한, 다른 것들과 구별되는 / (형) 구별되는, 특유의"),
        Word(english: "plumbing", korean: "(명) 배관 작업, 설비"),
        Word(english: "daily", korean: "(형) 매일의 / (부) 매일"),
        Word(english: "coincide", korean: "(동) 동시에 발생하다 / (동) 일치하다"),
        Word(english: "improvement", korean: "(명) 개선, 향상 / (명) 개선된 것, 개량품"),
        Word(english: "anecdote", korean: "(명) 짧은 이야기, 일화"),
        Word(english: "enrollment", korean: "(명) 등록, 입학 / (명) 등록자 수"),
        Word(english: "avid", korean: "(형) 열렬한, 열광적인"),
        Word(english: "indoor", korean: "(형) 실내의"),
        Word(english: "critically", korean: "(부) 비판적으로 / (부) 결정적으로"),
        Word(english: "socialize", korean: "(동) 사람들과 어울리다 / (동) 친화적인 환경을 조성하 다"),
        Word(english: "develop", korean: "(동) 개발하다 / (동) 발달하다"),
        Word(english: "culminate", korean: "(동) 최고조에 달하다 / (동) 끝이 나다, 마무리되다"),
        Word(english: "acclaimed", korean: "(형) 칭찬받는, 호평을 받 는"),
        Word(english: "care", korean: "(명) 주의, 신경 씀 / (명) 돌봄, 관리"),
        Word(english: "ergonomic", korean: "(형) 인체공학적인"),
        Word(english: "relaxed", korean: "(형) 긴장이 풀린, 편안한 / (형) 느긋한"),
        Word(english: "notable", korean: "(형) 주목할 만한, 중요한 / (명) 유명인사, 저명한 사람"),
        Word(english: "richly", korean: "(부) 풍부하게 / (부) 충분히"),
        Word(english: "strategically", korean: "(부) 전략적으로"),
        Word(english: "borrow", korean: "(동) 빌리다"),
        Word(english: "appendix", korean: "(명) 부록 / (명) 맹장"),
        Word(english: "autobiography", korean: "(명) 자서전"),
        Word(english: "inaccuracy", korean: "(명) 부정확성, 오류 / (명) 불명확함"),
        Word(english: "affiliation", korean: "(명) 소속, 연계"),
        Word(english: "capability", korean: "(명) 능력, 역량"),
        Word(english: "casually", korean: "(부) 비공식적으로, 편하게 / (부) 무심코, 우연히"),
        Word(english: "inspection", korean: "(명) 검사, 점검 / (명) 사찰, 감찰"),
        Word(english: "mental", korean: "(형) 정신의, 마음의"),
        Word(english: "infectious", korean: "(형) 전염성의 / (형) 전염력이 있는 (감정 등)"),
        Word(english: "conservation", korean: "(명) 보존, 보호 / (명) 절약"),
        Word(english: "splendor", korean: "(명) 화려함, 웅장함"),
        Word(english: "ancient", korean: "(형) 고대의, 오래된 / (명) 고대인"),
        Word(english: "flooding", korean: "(명) 홍수"),
        Word(english: "disappointed", korean: "(형) 실망한"),
        Word(english: "frustrated", korean: "(형) 좌절감을 느끼는 / (명) 좌절, 불만"),
        Word(english: "breathtakingly", korean: "(부) 숨 막히게, 놀랍게도 / (형) 숨 막히는, 놀라운"),
        Word(english: "delighted", korean: "(형) 매우 기쁜 / (형) 즐거운"),
        Word(english: "familiar", korean: "(형) 익숙한, 잘 알고 있는 / (형) 친숙한, 익숙한"),
        Word(english: "uncomfortably", korean: "(부) 불편하게"),
        Word(english: "impressed", korean: "(동) 깊은 인상을 주다 / (동) 감동을 주다"),
        Word(english: "convinced", korean: "(형) 확신한 / (형) 확신시키다, 설득시키다"),
        Word(english: "afraid", korean: "(형) 두려워하는, 겁내는 / (형) 걱정하는"),
        Word(english: "bring", korean: "(동) 가져오다 / (동) (사람을) 데려오다"),
        Word(english: "infrequently", korean: "(부) 드물게, 가끔 / (부) 빈번하지 않게"),
        Word(english: "rectangular", korean: "(형) 직사각형의 / (형) 직각의"),
        Word(english: "substance", korean: "(명) 물질, 소재 / (명) 핵심, 요지"),
        Word(english: "luxury", korean: "(명) 사치, 호화 / (형) 고급의, 사치스러운"),
        Word(english: "story", korean: "(명) 이야기 / (명) 기사, 보도"),
        Word(english: "fear", korean: "(명) 두려움, 공포 / (동) 두려워하다"),
        Word(english: "element", korean: "(명) 요소, 구성 부분 / (명) 환경, 기분"),
        Word(english: "solid", korean: "(형) 고체의, 단단한 / (형) 견고한, 신뢰할 수 있는"),
        Word(english: "adjustable", korean: "(형) 조정 가능한, 변경 가 능한"),
        Word(english: "trend", korean: "(명) 경향, 추세"),
        Word(english: "activity", korean: "(명) 활동 / (명) 업무"),
        Word(english: "rage", korean: "(명) 분노 / (동) 격노하다, 격렬하게 지속 되다"),
        Word(english: "ultimate", korean: "(형) 최종의, 궁극적인 / (형) 최고(최상)의"),
        Word(english: "tie", korean: "(동) 묶다 / (동) 동점이 되다"),
        Word(english: "screw", korean: "(명) 나사, 나사못 / (동) 조이다, 고정하다"),
        Word(english: "supervise", korean: "(동) 감독하다 / (동) 지도하다"),
        Word(english: "bound", korean: "(형) 묶인, 구속된 / (형) ~할 가능성이 있는, ~할 의무가 있는"),
        Word(english: "plot", korean: "(명) 줄거리, 구성 / (명) 음모, 모의"),
        Word(english: "distinction", korean: "(명) 차이점, 구별 / (명) 우수성, 영예"),
        Word(english: "miserable", korean: "(형) 매우 불행한 / (형) 열악한, 비참한"),
        Word(english: "practice", korean: "(명) 실행, 실습, 연습 / (명) 관습, 관례"),
        Word(english: "prime", korean: "(형) 주요한, 최상의 / (명) 전성기"),
        Word(english: "well-being", korean: "(명) 복지, 웰빙"),
        Word(english: "obligation", korean: "(명) 의무, 책임 / (명) 채무, 채권"),
        Word(english: "neglect", korean: "(동) 무시하다, 소홀히 하 다 / (명) 무시, 소홀"),
        Word(english: "omit", korean: "(동) 생략하다 / (동) 빠뜨리다"),
        Word(english: "modest", korean: "(형) 겸손한 / (형) 적당한"),
        Word(english: "affair", korean: "(명) 사건, 일 / (명) 연애관계"),
        Word(english: "split", korean: "(동) 나누다 / (명) 분할, 불일치"),
        Word(english: "conceal", korean: "(동) 숨기다, 감추다"),
        Word(english: "decent", korean: "(형) 괜찮은, 품질이 나쁘 지 않은 / (형) 적절한, 예의 바른"),
        Word(english: "pace", korean: "(명) 속도 / (동) 천천히 걷다, 서성거리다"),
        Word(english: "insider", korean: "(명) 내부자"),
        Word(english: "sanction", korean: "(명) 제재, 처벌 / (동) 허가하다, 승인하다"),
        Word(english: "circuit", korean: "(명) 회로 / (명) 순회, 둘레"),
        Word(english: "combine", korean: "(동) 결합하다 / (동) 협력하다"),
        Word(english: "adjust", korean: "(동) 조정하다, 맞추다 / (동) 적응하다, 익숙해지다"),
        Word(english: "accommodate", korean: "(동) (사람, 물건을) 수용하 다 / (동) (요청, 필요를) 충족시키 다"),
        Word(english: "subject", korean: "(명) 주제, 화제 / (명) 과목"),
        Word(english: "delegate", korean: "(명) 대표자, 대리인 / (동) 권한을 위임하다"),
        Word(english: "locate", korean: "(동) 찾다 / (동) 두다"),
        Word(english: "represent", korean: "(동) 대표하다 / (동) 설명하다, 나타내다"),
        Word(english: "claim", korean: "(명) 주장, 요구 / (동) 주장하다"),
        Word(english: "indicate", korean: "(동) 가리키다, 지시하다 / (동) 나타내다, 암시하다"),
        Word(english: "brief", korean: "(형) 짧은, 간단한 / (동) 요약하다, 설명하다"),
        Word(english: "commence", korean: "(동) 시작하다 / (동) 착수하다"),
        Word(english: "lower", korean: "(동) 낮추다, 내리다 / (형) 더 낮은, 하위의"),
        Word(english: "admission", korean: "(명) 입장 / (명) 입학"),
        Word(english: "browse", korean: "(동) 훑어보다 / (동) 검색하다"),
        Word(english: "appetite", korean: "(명) 식욕 / (명) 욕망, 욕구"),
        Word(english: "quality", korean: "(명) 품질 / (명) 특성, 성질"),
        Word(english: "honor", korean: "(명) 명예, 영예 / (동) 존경하다, 경의를 표하다"),
        Word(english: "attendance", korean: "(명) 출석, 참석 / (명) 출석율"),
        Word(english: "defy", korean: "(동) 반항하다, 도전하다 / (동) 무시하다, 거부하다"),
        Word(english: "condense", korean: "(동) 간추리다, 요약하다 / (동) 응축하다, 압축하다"),
        Word(english: "readily", korean: "(부) 쉽게 / (부) 즉시"),
        Word(english: "diversify", korean: "(동) 다양화하다, 다각화하 다 / (동) 다변화하다"),
        Word(english: "purpose", korean: "(명) 목적, 의도 / (명) 용도"),
        Word(english: "remarkable", korean: "(형) 눈에 띄는, 주목할 만 한 / (형) 놀라운"),
        Word(english: "accuse", korean: "(동) 비난하다 / (동) 범죄 혐의를 부과하다"),
        Word(english: "coordinate", korean: "(동) 조율하다, 조정하다 / (동) 협력하다"),
        Word(english: "breakthrough", korean: "(명) 중요한 발견 / (명) 돌파구, 진전"),
        Word(english: "affiliate", korean: "(동) 제휴하다 / (명) 계열사, 제휴 기관"),
        Word(english: "aggravate", korean: "(동) 악화시키다"),
        Word(english: "amend", korean: "(동) 수정하다, 변경하다 / (동) 개정하다, 보완하다"),
        Word(english: "collateral", korean: "(명) 담보(물) / (형) 부수적인"),
        Word(english: "compulsory", korean: "(형) 강제된, 의무적인 / (형) 필수"),
        Word(english: "prosecute", korean: "(동) 법적으로 기소하다 / (동) 수행하다, 추진하다"),
        Word(english: "promising", korean: "(형) 전도유망한, 기대되는 / (형) 장래성 있는"),
        Word(english: "volatile", korean: "(형) 변덕스러운 / (형) 휘발성의"),
        Word(english: "surpass", korean: "(동) 능가하다 / (동) 초과하다"),
        Word(english: "vulnerable", korean: "(형) 취약한"),
        Word(english: "subordinate", korean: "(형) 하위의, 종속적인 / (명) 부하직원, 하급자"),
        Word(english: "incur", korean: "(동) (비용을) 발생시키다 / (동) (손해를) 초래하다"),
        Word(english: "overall", korean: "(형) 전반적인 / (부) 전반적으로, 전체적으로"),
        Word(english: "quota", korean: "(명) 할당량 / (명) 정량"),
        Word(english: "oversee", korean: "(동) 관리하다, 감독하다"),
        Word(english: "subsidiary", korean: "(형) 보조적인, 부수적인 / (명) 자회사"),
        Word(english: "morale", korean: "(명) 사기, 의욕 / (명) 군대나 조직 내의 사기"),
        Word(english: "prolonged", korean: "(형) 장기적인, 길어진"),
        Word(english: "bid", korean: "(동) 제안하다, 입찰하다 / (명) 입찰, 제안"),
        Word(english: "recipient", korean: "(명) 수령인, 받는 사람"),
        Word(english: "mortgage", korean: "(명) 담보 대출 / (동) 담보로 잡히다"),
        Word(english: "assign", korean: "(동) 할당하다, 배정하다 / (동) 임명하다, 지정하다"),
        Word(english: "assert", korean: "(동) 주장하다 / (동) (권리 등을) 강하게 주장 하다"),
        Word(english: "convince", korean: "(동) 설득하다, 납득시키다"),
        Word(english: "allowance", korean: "(명) 허용량 / (명) 수당"),
        Word(english: "entry", korean: "(명) 입장, 들어감 / (명) 기재, 기록된 항목"),
        Word(english: "specification", korean: "(명) 명세서, 사양"),
        Word(english: "consecutive", korean: "(형) 연속적인"),
        Word(english: "substantial", korean: "(형) 상당한 / (형) 튼튼한, 단단한"),
        Word(english: "takeover", korean: "(명) 기업 인수 / (명) 장악, 점령"),
        Word(english: "proprietor", korean: "(명) 소유주"),
        Word(english: "campaign", korean: "(명) 캠페인, 운동, 활동 / (동) 캠페인을 벌이다, 운동을 하다"),
        Word(english: "invaluable", korean: "(형) 매우 귀중한, 가치를 매길 수 없는"),
        Word(english: "conclude", korean: "(동) 마무리하다 / (동) 결론을 내리다"),
        Word(english: "secure", korean: "(동) 안전하게 하다 / (동) 확보하다"),
        Word(english: "fabulous", korean: "(형) 아주 멋진, 훌륭한 / (형) 터무니없는, 믿기 어려운"),
        Word(english: "agreement", korean: "(명) 계약, 합의 / (명) 일치, 동의"),
        Word(english: "barely", korean: "(부) 겨우, 간신히 / (부) 거의 ~않다"),
        Word(english: "objective", korean: "(명) 목표, 목적 / (형) 객관적인"),
        Word(english: "evaluation", korean: "(명) 평가"),
        Word(english: "level", korean: "(명) 수준, 단계 / (형) 평평한, 수평의"),
        Word(english: "colleague", korean: "(명) 동료"),
        Word(english: "force", korean: "(명) 힘, 물리력 / (명) 군대, 특정 부대"),
        Word(english: "premier", korean: "(형) 최고의, 가장 중요한 / (명) 수상, 총리"),
        Word(english: "hostile", korean: "(형) 적대적인 / (형) 불리한, 위험한"),
        Word(english: "correspond", korean: "(동) 소통하다, 연락하다 / (동) 일치하다, 상응하다"),
        Word(english: "fund", korean: "(명) 자금, 기금 / (동) 자금을 제공하다"),
        Word(english: "overlook", korean: "(동) 간과하다, 무시하다 / (동) 내려다보다"),
        Word(english: "raise", korean: "(동) 들어올리다 / (동) (수준이나 양을) 증가시 키다"),
        Word(english: "apply", korean: "(동) 지원하다 / (동) 적용하다"),
        Word(english: "audit", korean: "(명) 회계 감사 / (동) 감사하다, 검토하다"),
        Word(english: "accurately", korean: "(부) 정확하게"),
        Word(english: "bear", korean: "(동) 견디다, 참다 / (동) 출산하다"),
        Word(english: "consequence", korean: "(명) 결과, 영향"),
        Word(english: "alliance", korean: "(명) 동맹, 연합"),
        Word(english: "deter", korean: "(동) 단념시키다 / (동) 방해하다"),
        Word(english: "liable", korean: "(형) 책임이 있는 / (형) 하기 쉬운"),
        Word(english: "segment", korean: "(명) 부분, 조각 / (동) 나누다, 분할하다"),
        Word(english: "initiate", korean: "(동) 시작하다, 개시하다 / (동) 입문시키다, 가입시키다"),
        Word(english: "initially", korean: "(부) 처음에, 초기에"),
        Word(english: "contestant", korean: "(명) 경쟁자, 참가자"),
        Word(english: "substantially", korean: "(부) 상당히 / (부) 대체로, 주로"),
        Word(english: "automate", korean: "(동) 자동화하다"),
        Word(english: "pharmaceutical", korean: "(명) 의약품 / (형) 약학의, 제약의"),
        Word(english: "execute", korean: "(동) 실행하다 / (동) 법적 문서를 작성하다"),
        Word(english: "instruct", korean: "(동) 지시하다 / (동) 교육하다"),
        Word(english: "acquaint", korean: "(동) 알리다 / (동) 익숙하게 하다"),
        Word(english: "overprice", korean: "(동) 가격을 지나치게 높 게 책정하다"),
        Word(english: "pioneer", korean: "(명) 개척자, 선구자 / (동) 개척하다"),
        Word(english: "distinguished", korean: "(형) 두드러진, 뛰어난 / (형) 성공적이고 존경받는"),
        Word(english: "clearance", korean: "(명) 허가 / (명) 정리, 제거"),
        Word(english: "perceive", korean: "(동) 인식하다, 이해하다 / (동) 느끼다, 감지하다"),
        Word(english: "unify", korean: "(동) 통합하다, 하나로 만 들다"),
        Word(english: "incorporate", korean: "(동) 포함하다 / (동) 합병하다, 통합하다"),
        Word(english: "dismiss", korean: "(동) 해고하다 / (동) 일축하다, 무시하다"),
        Word(english: "interoffice", korean: "(형) 사무실 간의, 회사 내 의"),
        Word(english: "leisure", korean: "(명) 여가, 자유 시간 / (형) 여유로운, 느긋한"),
        Word(english: "suspect", korean: "(명) 용의자 / (동) 의심하다, 혐의를 두다"),
        Word(english: "graduate", korean: "(명) 졸업생 / (동) 졸업하다"),
        Word(english: "absurd", korean: "(형) 터무니없는 / (형) 불합리한"),
        Word(english: "academic", korean: "(형) 학문적인 / (명) 학자"),
        Word(english: "household", korean: "(명) 가정 / (형) 가정의, 가정에서 사용하 는"),
        Word(english: "proclaim", korean: "(동) 선언하다, 공표하다 / (동) 알리다, 공언하다"),
        Word(english: "reject", korean: "(동) 거부하다 / (동) 불합격 처리하다"),
        Word(english: "relative", korean: "(명) 친척 / (형) 비교적, 상대적인"),
        Word(english: "exaggerate", korean: "(동) 과장하다"),
        Word(english: "pose", korean: "(동) 질문을 제기하다 / (동) 포즈를 취하다"),
        Word(english: "bruise", korean: "(명) 멍, 타박상 / (동) 멍들게 하다, 상처를 주 다"),
        Word(english: "primary", korean: "(형) 주요한, 기본적인 / (형) 초등의, 초기의"),
        Word(english: "administration", korean: "(명) 관리, 경영 / (명) 정부 기관"),
        Word(english: "agency", korean: "(명) 대행사, 기관 / (명) 중개, 주선"),
        Word(english: "witness", korean: "(명) 증인 / (동) 목격하다"),
        Word(english: "layout", korean: "(명) 배치, 구성"),
        Word(english: "blueprint", korean: "(명) 설계도, 청사진 / (명) 상세 계획, 계획안"),
        Word(english: "qualified", korean: "(형) 자격이 있는 / (형) 제한적인, 조건부의"),
        Word(english: "recall", korean: "(동) 기억해내다 / (동) 회수하다"),
        Word(english: "distributor", korean: "(명) 유통업자, 배급사 / (명) 배전 장치 (자동차 엔진 부품)"),
        Word(english: "verify", korean: "(동) 확인하다, 검증하다 / (동) 입증하다"),
        Word(english: "restructure", korean: "(동) 조직 구조를 재편성 하다 / (동) 체제를 개혁하다"),
        Word(english: "pier", korean: "(명) 부두 / (명) 교각"),
        Word(english: "built-in", korean: "(형) 내장된 / (형) 기본으로 포함된"),
        Word(english: "dock", korean: "(명) 부두, 선착장 / (동) 정박시키다"),
        Word(english: "court", korean: "(명) 법정, 재판소 / (명) 궁정, 왕실"),
        Word(english: "burglar", korean: "(명) 도둑"),
        Word(english: "default", korean: "(명) 채무 불이행 / (명) 기본 설정"),
        Word(english: "evolve", korean: "(동) 발전하다, 진화하다 / (동) 점진적으로 변화하다"),
        Word(english: "gourmet", korean: "(명) 미식가 / (형) 고급의, 미식을 위한"),
        Word(english: "precision", korean: "(명) 정확성 / (명) 정밀도"),
        Word(english: "thesis", korean: "(명) 논문 / (명) 주제문, 주요 주장"),
        Word(english: "ventilate", korean: "(동) 환기하다 / (동) (감정을) 표현하다"),
        Word(english: "additive", korean: "(명) 첨가물 / (형) 부가적인, 첨가하는"),
        Word(english: "dismay", korean: "(명) 실망, 경악 / (동) 실망시키다, 경악하게 하 다"),
        Word(english: "shrewd", korean: "(형) 기민한, 날카로운"),
        Word(english: "stringent", korean: "(형) 엄격한"),
        Word(english: "credential", korean: "(명) 자격증, 신분 증명서 / (명) 학력, 경력"),
        Word(english: "lawsuit", korean: "(명) 소송"),
        Word(english: "plaintiff", korean: "(명) 원고, 소송 제기자 / (명) 고소인"),
        Word(english: "showcase", korean: "(동) 전시하다, 선보이다 / (명) 전시, 진열장"),
        Word(english: "preliminary", korean: "(형) 예비의, 초기의 / (명) 예비 단계, 준비 단계"),
        Word(english: "dean", korean: "(명) 학장 (특정 학과나 단과 대학의 최고 책임자) / (명) 오랜 경험자, 원로"),
        Word(english: "embezzle", korean: "(동) 자금을 횡령하다"),
        Word(english: "bureau", korean: "(명) 부서, 사무소 / (명) 사무 책상, 서랍"),
        Word(english: "resolution", korean: "(명) 해결, 결의안 / (명) 결심"),
        Word(english: "assent", korean: "(명) 동의, 찬성 / (동) 동의하다"),
        Word(english: "consciousness", korean: "(명) 의식, 자각 / (명) 관심, 인식"),
        Word(english: "linguistics", korean: "(명) 언어학"),
        Word(english: "liquor", korean: "(명) 증류주, 독한 술"),
        Word(english: "in-house", korean: "(형) 사내의, 내부의"),
        Word(english: "curator", korean: "(명) 전시 관장, 큐레이터 / (명) 관리자, 보호자"),
        Word(english: "dense", korean: "(형) 빽빽한 / (형) 짙은"),
        Word(english: "plunge", korean: "(명) 급락 / (동) 빠지다, 뛰어들다"),
        Word(english: "bribery", korean: "(명) 뇌물 수수, 부정행위"),
        Word(english: "forum", korean: "(명) 토론회, 포럼 / (명) 인터넷 포럼, 게시판"),
        Word(english: "fierce", korean: "(형) 격렬한, 강렬한 / (형) 사나운, 매우 공격적인"),
        Word(english: "collide", korean: "(동) 충돌하다, 맞부딪치다"),
        Word(english: "hygiene", korean: "(명) 위생, 위생관리"),
        Word(english: "lakeshore", korean: "(명) 호숫가"),
        Word(english: "starve", korean: "(동) 굶주리다, 배고파서 고생하다 / (동) (비유적으로) ~에 굶주리 다, 절실히 필요로 하다"),
        Word(english: "cardholder", korean: "(명) 카드 소유자"),
        Word(english: "getaway", korean: "(명) 휴양지, 휴가 장소 / (명) 도망, 탈출"),
        Word(english: "customary", korean: "(형) 관례적인, 일반적인"),
        Word(english: "pending", korean: "(형) 아직 미결된, 대기 중 인 / (전) ~동안, ~까지"),
        Word(english: "semiconductor", korean: "(명) 반도체"),
        Word(english: "workforce", korean: "(명) 노동력"),
        Word(english: "scheme", korean: "(명) 계획 / (명) 음모"),
        Word(english: "appetizer", korean: "(명) 전채 요리"),
        Word(english: "packaging", korean: "(명) 포장, 포장재"),
        Word(english: "stroll", korean: "(동) 느긋하게 걷다 / (명) 산책, 산보"),
        Word(english: "extravagant", korean: "(형) 지나치게 비싼, 사치 스러운 / (형) 낭비하는, 과도한"),
        Word(english: "lodge", korean: "(동) 머물다, 숙박하다 / (동) 제기하다"),
        Word(english: "drawback", korean: "(명) 장애물, 결점"),
        Word(english: "prototype", korean: "(명) 초기 모델, 원형 / (명) 원형, 시제품"),
        Word(english: "counterpart", korean: "(명) 상대방, 대응물"),
        Word(english: "knowledgeable", korean: "(명) 지식 / (명) 정보"),
        Word(english: "janitor", korean: "(명) 관리인"),
        Word(english: "core", korean: "(명) 핵심 / (형) 핵심적인"),
        Word(english: "pastor", korean: "(명) 목사, 성직자"),
        Word(english: "continental", korean: "(형) 대륙의 / (형) 대륙풍의, 대륙성의"),
        Word(english: "tune", korean: "(명) 곡, 음악 선율 / (동) 조율하다"),
        Word(english: "feasibility", korean: "(명) 실현 가능성"),
        Word(english: "vegetarian", korean: "(명) 채식주의자 / (형) 채식주의자의"),
        Word(english: "coalition", korean: "(명) 연합, 동맹 / (명) 합병"),
        Word(english: "integration", korean: "(명) 통합"),
        Word(english: "track", korean: "(동) 추적하다 / (명) 경로, 선로"),
        Word(english: "theme", korean: "(명) 주제, 테마"),
        Word(english: "insight", korean: "(명) 통찰, 이해"),
        Word(english: "housing", korean: "(명) 주택, 주거 / (명) 숙소, 주거지"),
        Word(english: "nearby", korean: "(형) 가까운 / (부) 가까이에, 근처에"),
        Word(english: "urge", korean: "(동) 강력히 권고하다, 촉 구하다 / (명) 강한 충동, 욕구"),
        Word(english: "outline", korean: "(명) 개요, 윤곽 / (동) 개요를 작성하다"),
        Word(english: "particular", korean: "(형) 특정한 / (형) 특별한"),
        Word(english: "anchor", korean: "(명) 앵커(뉴스 진행자) / (명) 닻, 정박 장치"),
        Word(english: "competent", korean: "(형) 유능한, 능숙한 / (형) 적임의, 권한이 있는"),
        Word(english: "hassle", korean: "(명) 번거로움, 귀찮은 일 / (동) 귀찮게 하다, 괴롭히다"),
        Word(english: "promotional", korean: "(형) 촉진의, 홍보의"),
        Word(english: "resolve", korean: "(동) 해결하다 / (동) 결심하다"),
        Word(english: "scatter", korean: "(동) 흩뿌리다, 흩어지게 하다 / (동) 소량의 대상으로 흩뿌리 다"),
        Word(english: "downtown", korean: "(명) 도심, 시내 / (형) 도심의"),
        Word(english: "association", korean: "(명) 협회, 단체 / (명) 연관성, 관련"),
        Word(english: "retiree", korean: "(명) 은퇴자, 퇴직자"),
        Word(english: "identify", korean: "(동) 식별하다, 확인하다 / (동) 찾아내다"),
        Word(english: "proceeds", korean: "(명) 수익금 / (명) 총액"),
        Word(english: "gather", korean: "(동) 모으다, 수집하다 / (동) 모이다"),
        Word(english: "reside", korean: "(동) 거주하다 / (동) 존재하다"),
        Word(english: "light", korean: "(명) 빛, 조명 / (동) 불을 켜다, 밝게 하다"),
        Word(english: "assured", korean: "(형) 자신감 있는, 확신한 / (형) 보장된, 안전한"),
        Word(english: "erect", korean: "(동) 세우다, 건립하다 / (형) 똑바로 선, 직립한"),
        Word(english: "draw", korean: "(동) 그리다 / (동) 끌다"),
        Word(english: "kit", korean: "(명) 도구 세트 / (명) 장비 세트"),
        Word(english: "premiere", korean: "(명) 첫 공개, 초연 / (동) 초연하다, 첫 공개를 하 다"),
        Word(english: "dealership", korean: "(명) 판매 대리점, 판매권 / (명) 대리권"),
        Word(english: "furnace", korean: "(명) 용광로, 난로"),
        Word(english: "craft", korean: "(동) 정교하게 만들다 / (명) 수공예, 기술"),
        Word(english: "mind", korean: "(동) 신경 쓰다 / (동) 꺼리다"),
        Word(english: "artwork", korean: "(명) 예술 작품 / (명) 삽화, 디자인"),
        Word(english: "remark", korean: "(명) 발언, 논평 / (동) 주목하다, 언급하다"),
        Word(english: "offend", korean: "(동) 감정을 상하게 하다 / (동) 범죄를 저지르다"),
        Word(english: "agitate", korean: "(동) 불안하게 만들다 / (동) 선동하다, 자극하다"),
        Word(english: "cherish", korean: "(동) 소중히 여기다"),
        Word(english: "curfew", korean: "(명) 통행금지 / (명) 통금 시간"),
        Word(english: "delineate", korean: "(동) 상세히 설명하다 / (동) 윤곽을 그리다"),
        Word(english: "dire", korean: "(형) 심각한, 끔찍한 / (형) 음산한, 무서운"),
        Word(english: "eloquent", korean: "(형) 웅변의, 설득력 있는"),
        Word(english: "erode", korean: "(동) 침식되다, 마모되다 / (동) 약화시키다"),
        Word(english: "espionage", korean: "(명) 첩보 활동 / (명) 스파이 행위"),
        Word(english: "exude", korean: "(동) 어떤 특질이나 감정 을 발산하다 / (동) 흘러나오다"),
        Word(english: "founder", korean: "(명) 창립자, 설립자"),
        Word(english: "odds", korean: "(명) 확률, 가능성 / (명) 갈등, 의견 차이"),
        Word(english: "inquisitive", korean: "(형) 호기심이 많은 / (형) 호기심이 강한"),
        Word(english: "dissertation", korean: "(명) 논문"),
        Word(english: "overturn", korean: "(동) 뒤집다 / (동) 전복시키다"),
        Word(english: "tardy", korean: "(형) 늦은, 지연된"),
        Word(english: "undue", korean: "(형) 부당한 / (형) 지나친, 과도한"),
        Word(english: "vandalize", korean: "(동) 파손하다 / (동) 훼손하다"),
        Word(english: "vent", korean: "(명) 배출구, 통풍구 / (동) 감정을 표출하다"),
        Word(english: "placid", korean: "(형) 조용하고 평온한 / (형) 차분한"),
        Word(english: "ingenious", korean: "(형) 창의적인, 기발한 / (형) 정교하게 설계된"),
        Word(english: "disturb", korean: "(동) 방해하다 / (동) 어지럽히다"),
        Word(english: "acquaintance", korean: "(명) 아는 사람, 지인 / (명) 면식, 친분"),
        Word(english: "provoke", korean: "(동) 특정 반응을 유발하 다 / (동) 화나게 하다"),
        Word(english: "attest", korean: "(동) 증명하다 / (동) 확인하다"),
        Word(english: "entrust", korean: "(동) 책임을 맡기다, 위임 하다 / (동) 신뢰하고 맡기다"),
        Word(english: "reputable", korean: "(형) 평판이 좋은"),
        Word(english: "abridge", korean: "(동) 요약하다, 단축하다"),
        Word(english: "roam", korean: "(동) 돌아다니다, 방황하다"),
        Word(english: "scary", korean: "(형) 무서운, 두려운 / (형) 겁을 주는"),
        Word(english: "compost", korean: "(명) 퇴비 / (동) 퇴비로 만들다"),
        Word(english: "criteria", korean: "(명) 기준, 조건 / (명) 단일 기준"),
        Word(english: "transmission", korean: "(명) 전송, 전파 / (명) 전달, 전달력"),
        Word(english: "disapprove", korean: "(동) 반대하다 / (동) 승인하지 않다"),
        Word(english: "restructuring", korean: "(명) 구조 조정, 개편"),
        Word(english: "repression", korean: "(명) 억압 / (명) 억제 (감정)"),
        Word(english: "treadmill", korean: "(명) 런닝머신 / (명) 반복적이고 지루한 일상"),
        Word(english: "portion", korean: "(명) 부분 / (명) 1인분"),
        Word(english: "further", korean: "(형) 추가적인 / (부) 1 더 나아가, 더 멀리"),
        Word(english: "settlement", korean: "(명) 합의, 해결 / (명) 정착지"),
        Word(english: "discretion", korean: "(명) 신중함 / (명) 재량, 자유 재량권"),
        Word(english: "prominently", korean: "(부) 눈에 띄게"),
        Word(english: "construe", korean: "(동) 해석하다, 이해하다"),
        Word(english: "meanwhile는", korean: "(부) 그 동안에"),
        Word(english: "reparation", korean: "(명) 배상, 보상 / (명) 수리, 수선"),
        Word(english: "scare", korean: "(동) 겁주다, 놀라게 하다 / (명) 공포, 흠칫 놀람"),
        Word(english: "daunting", korean: "(형) 주눅 들게 하는, 벅찬"),
        Word(english: "marginally", korean: "(부) 아주 조금, 미미하게"),
        Word(english: "schooling", korean: "(명) 정규 교육 / (명) 훈련"),
        Word(english: "frequency", korean: "(명) 빈도 / (명) 주파수"),
        Word(english: "override", korean: "(동) 무시하다 / (동) 기각하다"),
        Word(english: "showroom", korean: "(명) 전시실, 전시장"),
        Word(english: "broadband", korean: "(명) 고속 인터넷 / (형) 광역 통신망의"),
        Word(english: "dreadfully", korean: "(부) 무서운 정도로, 몹시"),
        Word(english: "reassurance", korean: "(명) 안심"),
        Word(english: "oppression", korean: "(명) 억압"),
        Word(english: "dreadful", korean: "(형) 무서운, 끔찍한"),
        Word(english: "conspire", korean: "(동) 공모하다, 음모를 꾸 미다 / (동) (어떤 일이) 함께 일어나다, 공통 원인으로 작용하다"),
        Word(english: "deed", korean: "(명) 행위, 업적 / (명) 법적 문서, 증서(특히 부 동산 거래)"),
        Word(english: "entry-level", korean: "(형) 초급의"),
        Word(english: "alumnus", korean: "(명) 남성 졸업생"),
        Word(english: "buyout", korean: "(명) 매수"),
        Word(english: "sanctions", korean: "(명) 제재 / (동) 허가하다, 승인하다"),
        Word(english: "skewed", korean: "(형) 편향된, 왜곡된"),
        Word(english: "conscription", korean: "(명) 징병"),
        Word(english: "altercate", korean: "(동) 말다툼하다, 언쟁하다"),
        Word(english: "usage", korean: "(명) 사용(량), 용법 / (명) 이용 빈도"),
        Word(english: "distress", korean: "(명) 심한 고통, 괴로움 / (동) 괴롭게 하다, 고통스럽게 하다"),
        Word(english: "approximate", korean: "(형) 대략적인 / (동) 대략적으로 추정하다"),
        Word(english: "financing", korean: "(명) 자금 조달"),
        Word(english: "credibly", korean: "(부) 신빙성 있게"),
        Word(english: "organization", korean: "(명) 조직, 단체 / (명) 구성, 체계"),
        Word(english: "viciously", korean: "(부) 잔인하게 / (부) 악의적으로"),
        Word(english: "deteriorative", korean: "(형) 악화시키는 / (동) 악화되다"),
        Word(english: "submit", korean: "(동) 제출하다 / (동) 복종하다"),
        Word(english: "strain", korean: "(명) 긴장, 압박 / (동) 무리하게 사용하다, 긴장 시키다"),
        Word(english: "revitalize", korean: "(동) 새로운 활력을 주다 / (동) 재활성화하다"),
        Word(english: "bonanza", korean: "(명) 노다지, 대박 / (명) 풍부한 원천"),
        Word(english: "publicize", korean: "(동) 공개하다 / (동) 홍보하다"),
        Word(english: "enforcement", korean: "(명) 집행, 시행"),
        Word(english: "assertiveness", korean: "(명) 단호하게 주장하는 능력 / (형) 단호한"),
        Word(english: "proactive", korean: "(형) 사전 예방적인"),
        Word(english: "advancement", korean: "(명) 진보, 발전 / (명) 승진"),
        Word(english: "bin", korean: "(명) 쓰레기통 / (명) 저장 용기"),
        Word(english: "chapter", korean: "(명) (책의) 장, 단원 / (명) (역사나 삶의) 특정 시기"),
        Word(english: "undesirable", korean: "(형) 원하지 않는, 바람직 하지 않은"),
        Word(english: "ground", korean: "(명) 땅, 지면 / (명) 기반, 기초"),
        Word(english: "corresponding", korean: "(형) 일치하는 / (형) 관련 있는"),
        Word(english: "curbside", korean: "(명) 도로 경계선 근처"),
        Word(english: "sanitation", korean: "(명) 위생 / (명) 위생 시설"),
        Word(english: "against", korean: "(전) 반대하여 / (전) 맞서서"),
        Word(english: "bag", korean: "(명) 가방 / (동) 획득하다"),
        Word(english: "outlying", korean: "(형) 외곽의, 멀리 떨어진"),
        Word(english: "re-energize", korean: "(동) 새로운 활력을 주다"),
        Word(english: "exemption", korean: "(명) 면제, 예외 / (명) 특례, 특별 허가"),
        Word(english: "high-profile", korean: "(형) 세간의 이목을 끄는, 유명한 / (형) 고위직의, 중요한"),
        Word(english: "publicist", korean: "(명) 홍보 전문가, 홍보 담 당자"),
        Word(english: "forgiveness", korean: "(명) 용서"),
        Word(english: "shaft", korean: "(명) 회전축 / (명) 수직 통로"),
        Word(english: "outsource", korean: "(동) 외주를 주다, 외부에 위탁하다 / (동) 외부 자원을 이용하다"),
        Word(english: "horseplay", korean: "(명) 장난, 거친 놀이"),
        Word(english: "encase", korean: "(동) 감싸다, 둘러싸다"),
        Word(english: "amphitheater", korean: "(명) 고대 로마식 원형 경 기장 / (명) 계단식 좌석 구조로 된 대형 공연장"),
        Word(english: "hiatus", korean: "(명) 중단, 휴식"),
        Word(english: "reconvene", korean: "(동) 다시 모이다 / (동) 회의를 재개하다"),
        Word(english: "perennial", korean: "(형) 다년생의 / (형) 지속적인, 영구적인"),
        Word(english: "cheer", korean: "(동) 환호하다, 응원하다 / (명) 환호, 응원"),
        Word(english: "congregate", korean: "(동) 모이다 / (형) 모인"),
        Word(english: "stellar", korean: "(형) 별의 / (형) 우수한"),
        Word(english: "phenomenal", korean: "(형) 경이적인, 놀라운 / (형) 자연 현상의"),
        Word(english: "admittedly", korean: "(부) 인정하건대"),
        Word(english: "admittance", korean: "(명) 입장, 허가"),
        Word(english: "defection", korean: "(명) 탈주"),
        Word(english: "acting", korean: "(명) 연기 / (형) 대행하는, 임시의"),
        Word(english: "plainly", korean: "(부) 명확하게, 분명히 / (부) 솔직하게"),
        Word(english: "concretely", korean: "(부) 구체적으로"),
        Word(english: "inarticulate", korean: "(형) 표현을 잘하지 못하 는 / (형) 발음이 명확하지 않은"),
        Word(english: "advantageous", korean: "(형) 유리한, 유익한 / (형) 이점이 있는"),
        Word(english: "winning", korean: "(형) 이긴, 승리한 / (명) 승리, 성공"),
        Word(english: "dresser", korean: "(명) 드레스 서랍장 / (명) 의상 담당자, 옷을 입히 는 사람"),
        Word(english: "likelihood", korean: "(명) 가능성 / (명) 확률"),
        Word(english: "eccentricity", korean: "(명) 특이함, 기이함"),
        Word(english: "admirably", korean: "(부) 감탄할 정도로 / (부) 칭찬할 만하게"),
        Word(english: "substantiate", korean: "(동) 증명하다"),
        Word(english: "sever", korean: "(동) (물리적으로) 절단하 다 / (동) (관계 등을) 끊다"),
        Word(english: "sensible", korean: "(형) 합리적인, 분별 있는 / (형) 지각 있는, 감각이 있는"),
        Word(english: "economize", korean: "(동) 절약하다, 아끼다"),
        Word(english: "preconditioned", korean: "(동) 미리 조건을 맞추다"),
        Word(english: "indistinctly", korean: "(부) 분명하지 않게"),
        Word(english: "discussion", korean: "(명) 논의, 토론"),
        Word(english: "procession", korean: "(명) 행렬, 행진 / (명) 연속"),
        Word(english: "proscription", korean: "(명) 금지 / (명) 제명"),
        Word(english: "vet", korean: "(명) 수의사 / (동) 철저히 조사하다"),
        Word(english: "amid", korean: "(전) ~의 한가운데에 / (전) ~에 둘러싸여"),
        Word(english: "disreputable", korean: "(형) 평판이 좋지 않은"),
        Word(english: "tad", korean: "(명) 약간, 조금"),
        Word(english: "ferocity", korean: "(명) 격렬함, 사나움, 잔인 함 / (명) 격렬함, 열정"),
        Word(english: "intent", korean: "(명) 의도, 목적 / (형) 몰두한, 열중한"),
        Word(english: "prioritize", korean: "(동) 우선순위를 정하다 / (동) 우선권을 부여하다"),
        Word(english: "accentuate", korean: "(동) 강조하다 / (동) 두드러지게 하다"),
        Word(english: "mailer", korean: "(명) 우편 발송물 / (명) 우편물 수발자"),
        Word(english: "understated", korean: "(형) 절제된, 과장되지 않 은 / 분사 과소평가하다"),
        Word(english: "communal", korean: "(형) 공동의, 공유의 / (형) 공공의, 공용의"),
        Word(english: "encrusted", korean: "(형) 껍질로 덮인 / (형) (오물 등으로) 덮인"),
        Word(english: "whereabouts", korean: "(명) 행방, 소재 / (부) 어디쯤, 어느 곳에"),
        Word(english: "notify", korean: "(동) 통지하다, 알리다"),
        Word(english: "explicitly", korean: "(부) 명확하게 / (부) 분명히"),
        Word(english: "implausible", korean: "(형) 사실일 것 같지 않은"),
        Word(english: "acutely", korean: "(부) 심하게, 몹시 / (부) 강하게, 예리하게"),
        Word(english: "repudiation", korean: "(명) 거부, 거절 / (명) 부인"),
        Word(english: "inconceivable", korean: "(형) 상상할 수 없는 / (형) 이해할 수 없는"),
        Word(english: "gratifyingly", korean: "(부) 기쁘게도"),
        Word(english: "openness", korean: "(명) 개방성 / (명) 솔직함"),
        Word(english: "mature", korean: "(형) 성숙한 / (형) 완전히 성장한"),
        Word(english: "repetition", korean: "(명) 반복"),
        Word(english: "intrusive", korean: "(형) 끼어드는, 방해하는 / (형) 강요하는 듯한"),
        Word(english: "wing", korean: "(명) 날개 / (동) 날다, 날아가다"),
        Word(english: "craftsmanship", korean: "(명) 장인 정신, 솜씨"),
        Word(english: "sonic", korean: "(형) 소리의, 음파의"),
        Word(english: "generalize", korean: "(동) 일반화하다 / (동) 전반적인 결론을 이끌어 내다"),
        Word(english: "implicate", korean: "(동) 연루시키다 / (동) 암시하다"),
        Word(english: "downplay", korean: "(동) 사소하게 여기다 / (동) 중요성을 낮추다"),
        Word(english: "naturally", korean: "(부) 자연스럽게 / (부) 당연히, 물론"),
        Word(english: "navigate", korean: "(동) 길을 찾다, 항해하다 / (동) (웹사이트, 시스템 등을) 탐색하다, 검색하다"),
        Word(english: "comprehend", korean: "(동) 이해하다 / (동) 포함하다"),
        Word(english: "perspective", korean: "(명) 관점, 시각"),
        Word(english: "photography", korean: "(명) 사진술, 사진 기술 / (명) 사진 촬영"),
        Word(english: "mastery", korean: "(명) 숙달, 완전한 이해 / (명) 지배, 통제"),
        Word(english: "representation", korean: "(명) 표현, 설명 / (명) 대표, 대변"),
        Word(english: "aesthetics", korean: "(명) 미적 감각 / (명) 미학"),
        Word(english: "repay", korean: "(동) 돈을 갚다 / (동) 보답하다"),
        Word(english: "repute", korean: "(명) 평판, 명성 / (동) 평가하다, 간주하다"),
        Word(english: "inevitability", korean: "(명) 불가피함, 피할 수 없 음"),
        Word(english: "high-rise", korean: "(형) 고층의 / (명) 고층 건물"),
        Word(english: "stream", korean: "(명) 흐름, 시내 / (동) 흐르다"),
        Word(english: "inland", korean: "(형) 내륙의 / (부) 내륙으로"),
        Word(english: "entries", korean: "(명) 참가자 목록, 항목 / (명) 입력, 출입"),
        Word(english: "paralegal", korean: "(명) 변호사 보조원"),
        Word(english: "kiosk", korean: "(명) 키오스크, 작은 매점"),
        Word(english: "abundance", korean: "(명) 풍부함"),
        Word(english: "refrigeration", korean: "(명) 냉각, 냉장"),
        Word(english: "patented", korean: "(형) 특허를 받은 / (동) 특허를 받다"),
        Word(english: "estimation", korean: "(명) 추정 / (명) 견적"),
        Word(english: "scam", korean: "(명) 사기 / (동) 사기 치다"),
        Word(english: "lodging", korean: "(명) 숙박, 숙소 / (명) 임시 주거"),
        Word(english: "fleet", korean: "(명) 차량이나 선박의 무 리 / (명) 함대, 전대"),
        Word(english: "cramped", korean: "(형) 좁고 불편한 / (형) 응축된, 불편하게 배열된"),
        Word(english: "approach", korean: "(명) 접근, 접근법 / (명) 접근, 방문"),
        Word(english: "rehearse", korean: "(동) 연습하다, 시연하다 / (동) 되풀이하다, 반복해서 말 하다"),
        Word(english: "heed", korean: "(동) 주의하다, 경청하다 / (명) 주의, 유의"),
        Word(english: "headhunting", korean: "(명) 인재 스카우트"),
        Word(english: "credibility", korean: "(명) 신뢰성"),
        Word(english: "decisively", korean: "(부) 결정적으로 / (부) 명확하게"),
        Word(english: "impractical", korean: "(형) 실용적이지 않다 / (명) 실용적이지 않음"),
        Word(english: "accent", korean: "(명) 강세, 억양 / (명) 특징, 강조"),
        Word(english: "descendant", korean: "(명) 자손, 후손 / (명) 하강하는 것"),
        Word(english: "damages", korean: "(명) 손해 배상금 / (명) 손해, 피해"),
        ]
    }
}

struct QuizStats: Codable {
    var totalSessions: Int = 0
    var totalCorrect: Int = 0
    var totalWrong: Int = 0
    var bestScore: Double = 0
    var lastPlayedDate: Date?
    var studyDates: [String] = []
    
    var totalQuestions: Int { totalCorrect + totalWrong }
    var overallAccuracy: Double {
        guard totalQuestions > 0 else { return 0 }
        return Double(totalCorrect) / Double(totalQuestions) * 100
    }
}
